#!/usr/bin/env node
// Regenerates src/api/schema.d.ts and src/api/models.ts from the manager's OpenAPI document.
//   pnpm gen:api                          dumps the document with `uv run` (no server needed)
//   SPLASH_GUI_OPENAPI=<url|file> pnpm gen:api   reads it from a running manager or a file
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const web = join(dirname(fileURLToPath(import.meta.url)), '..');
const repo = join(web, '..');
let source = process.env.SPLASH_GUI_OPENAPI;
if (!source) {
  const home = mkdtempSync(join(tmpdir(), 'splash-gui-openapi-'));
  const json = execFileSync(
    'uv',
    ['run', '--project', join(repo, 'manager'), 'python', '-c',
      'import json; from splash_gui.app import create_app; print(json.dumps(create_app().openapi()))'],
    { env: { ...process.env, SPLASH_GUI_HOME: home, SPLASH_GUI_SECRETS: 'memory' }, maxBuffer: 64 * 1024 * 1024 },
  ).toString();
  source = join(home, 'openapi.json');
  writeFileSync(source, json);
}
execFileSync('pnpm', ['exec', 'openapi-typescript', source, '-o', 'src/api/schema.d.ts'], { cwd: web, stdio: 'inherit' });

const doc = JSON.parse(source.startsWith('http') ? execFileSync('curl', ['-sf', source]).toString() : readFileSync(source, 'utf8'));
const names = Object.keys(doc.components?.schemas ?? {}).filter((n) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(n)).sort();
const out = [
  '/**',
  ' * GENERATED by scripts/gen-api.mjs from the manager OpenAPI document. Do not edit.',
  ' * Named aliases for components.schemas so pages can `import type { EngineView } from "../api/models"`.',
  ' */',
  "import type { components } from './schema';",
  '',
  "export type Schemas = components['schemas'];",
  ...names.map((n) => `export type ${n} = Schemas['${n}'];`),
  '',
].join('\n');
writeFileSync(join(web, 'src/api/models.ts'), out);
console.log(`src/api/models.ts: ${names.length} aliases`);
