/** Strings for the lower Status bands (docs/ui/02 §8–9): Memory, Cache, Scheduler, Latency and
 * Claude Code. Keys start with "bands.". They load with the lazily loaded bands, not with the
 * Status route's first paint (SPEC §18.6). Common keys come from ./en. */
import { en } from './en';
import { makeT } from './index';

export const bandsStrings = {
  'bands.bands.stopped': 'Engine stopped.',
  'bands.bands.not_reported': 'Not reported by this Splash version.',
  'bands.memory.label': 'Memory',
  'bands.memory.meter': 'Memory charged of limit',
  'bands.memory.charged': 'Charged of limit',
  'bands.memory.charged_v': '{c} of {l}',
  'bands.memory.current': 'Current · peak',
  'bands.memory.allocated': 'allocated {v}',
  'bands.memory.headroom': 'Headroom',
  'bands.memory.host': 'Host available · reserve',
  'bands.memory.host_of': 'of {ram} RAM · host headroom {v}',
  'bands.memory.pressure': 'Pressure',
  'bands.memory.pressure.normal': 'Normal',
  'bands.memory.pressure.warning': 'Warning',
  'bands.memory.pressure.critical': 'Critical',
  'bands.memory.top_pressure': 'engine memory_pressure: {v}',
  'bands.memory.growth': 'Growth',
  'bands.memory.growth.allowed': 'allowed',
  'bands.memory.growth.denied': 'denied',
  'bands.memory.denied': '{n} denied reservations',
  'bands.memory.metal': 'Metal',
  'bands.memory.metal_ok': 'healthy',
  'bands.memory.metal_failed': 'failed: {reason}',
  'bands.memory.explainer': 'Metal allocations, not process RSS.',
  'bands.cache.label': 'Cache',
  'bands.cache.ram': 'RAM',
  'bands.cache.pages': 'KV pages {a} active · {c} cached · {f} free of {t}',
  'bands.cache.kv_bytes': 'KV bytes {b} ({r} reclaimable)',
  'bands.cache.states': 'states {n} ({u} in use, {b})',
  'bands.cache.checkpoints': 'checkpoints {list}',
  'bands.cache.evictions': 'evictions {n}',
  'bands.cache.ssd': 'SSD tier',
  'bands.cache.ssd_meter': 'SSD cache used of capacity',
  'bands.cache.ssd_used': '{u} of {c}',
  'bands.cache.on_disk': 'on disk {v}',
  'bands.cache.kv_blocks': 'KV blocks {n} ({b})',
  'bands.cache.demotions': 'demotions {n} · refused {r} · pending pages {p}',
  'bands.cache.restores': 'restores {n}',
  'bands.cache.disk_hits': 'disk hits {h} · promotions {p} · offloads {o}',
  'bands.cache.wear': 'read {r} · written {w} this session',
  'bands.cache.off': 'Off',
  'bands.cache.settings': 'Cache settings',
  'bands.cache.persistent': 'Persistent',
  'bands.cache.persistent_on': 'On · {dir}',
  'bands.cache.persistent_off': 'Off · keeps the SSD cache across restarts',
  'bands.cache.taken_back': 'Restored at start: {s} states, {k} blocks, {b}, {l} left behind',
  'bands.cache.write_behind': 'write-behind waiting {w} · durable {d} · unneeded {u} · refused {r}',
  'bands.cache.failures': 'Failures',
  'bands.cache.f.copies': 'copies',
  'bands.cache.f.restores': 'restores',
  'bands.cache.f.offloads': 'offloads',
  'bands.cache.f.demotions': 'demotions',
  'bands.cache.f.replay': 'replay publications',
  'bands.cache.raw_failed': 'raw engine status',
  'bands.sched.label': 'Scheduler & admission',
  'bands.sched.waiting': 'Waiting',
  'bands.sched.waiting_v': '{t} total · {m} memory · {c} concurrency · {p} shared prefix · {g} grammar mask',
  'bands.sched.held': 'Held · restoring · suspended · draining',
  'bands.sched.held_v': '{h} held · {r} restoring · {s} suspended · draining {d}',
  'bands.sched.oldest': 'Oldest wait',
  'bands.sched.suspensions': 'Suspensions',
  'bands.sched.suspensions_v': '{r} resource · {p} priority · {m} resumed',
  'bands.sched.lanes': 'Lanes now',
  'bands.sched.lanes_v': '{p} prefilling · {d} decoding · {q} queued · {w} waiting for resources',
  'bands.sched.batches': 'Decode batches',
  'bands.sched.batches_aria': 'Decode batches by width: {list}',
  'bands.sched.loop': 'Loop',
  'bands.sched.loop_v': 'max tick {v}',
  'bands.latency.label': 'Latency',
  'bands.latency.caption': 'Latency per request stage',
  'bands.latency.stage': 'Stage',
  'bands.latency.p50': 'p50',
  'bands.latency.p95': 'p95',
  'bands.latency.mean': 'Mean',
  'bands.latency.count': 'Count',
  'bands.latency.approx': '≈ {v}',
  'bands.latency.note': 'p50 and p95 are estimated from Splash’s cumulative histogram buckets.',
  'bands.latency.missing': 'Not reported by this Splash version.',
  'bands.latency.raw': 'Raw buckets',
  'bands.latency.raw_stage': 'Stage',
  'bands.latency.bound': 'At most (s)',
  'bands.latency.cumulative': 'Cumulative count',
  'bands.latency.s.http_request': 'HTTP request',
  'bands.latency.s.upload': 'Upload',
  'bands.latency.s.preparation_queue': 'Preparation queue',
  'bands.latency.s.preparation': 'Preparation',
  'bands.latency.s.template': 'Template',
  'bands.latency.s.tokenization': 'Tokenization',
  'bands.latency.s.grammar': 'Grammar',
  'bands.latency.s.images': 'Images',
  'bands.latency.s.native_queue': 'Native queue',
  'bands.latency.s.http_ttft': 'Time to first token',
  'bands.latency.s.output_interval': 'Output interval',
  'bands.claude.label': 'Claude Code',
  'bands.claude.model': 'Model',
  'bands.claude.command': 'Command',
  'bands.claude.env': 'Environment variables',
  'bands.claude.reveal': 'Reveal key',
  'bands.claude.hide': 'Hide key',
  'bands.claude.copy_env': 'Copy',
  'bands.claude.copied': 'Copied',
  'bands.claude.key_failed': 'Couldn’t read the API key.',
  'bands.claude.alias': '{id} (alias)',
  'bands.claude.profile': '{id}',
  'bands.claude.stopped': 'The command starts the engine if needed.',
  'bands.claude.footer': 'Session-only: plain claude keeps its own account.',
  'bands.claude.integrations': 'Integrations',
  'bands.claude.integrations_more': 'for Codex, OpenCode, Hermes and Pi.',
  'bands.claude.no_model': 'No model to pick yet.',
} as const;

export const t = makeT({ ...en, ...bandsStrings });
