/** Chat strings (docs/ui/07). Keys start with "chat.". Common keys come from ./en. Model output is never in this table. */
import { en } from './en';
import { makeT } from './index';

export const chatStrings = {
  'chat.page_title': 'Chat',
  'chat.title': 'Chat.',
  'chat.doc_title': '{title} — Chat',
  'chat.default_title': 'New chat',

  // layout
  'chat.panel_toggle': 'Panel',
  'chat.list_toggle': 'Chats',
  'chat.list_sheet_title': 'Conversations.',
  'chat.panel_sheet_title': 'Panel.',
  'chat.thread_label': 'Conversation',

  // conversation list (07 §3)
  'chat.list.label': 'Conversations',
  'chat.list.search': 'Search conversations',
  'chat.list.search_placeholder': 'conversations…',
  'chat.list.new': '+ New chat',
  'chat.list.empty': 'No conversations yet.',
  'chat.list.no_match': 'No conversations match “{q}”.',
  'chat.list.results': 'Results ({n})',
  'chat.list.group.today': 'Today',
  'chat.list.group.yesterday': 'Yesterday',
  'chat.list.group.week': 'Previous 7 days',
  'chat.list.group.month': 'This month',
  'chat.list.group.older': 'Older',
  'chat.list.yesterday': 'Yesterday',
  'chat.list.rename': 'Rename',
  'chat.list.rename_label': 'New title for “{title}”',
  'chat.list.export': 'Export',
  'chat.list.export_json': 'JSON',
  'chat.list.export_md': 'Markdown',
  'chat.list.delete': 'Delete',
  'chat.list.streaming': 'Streaming',
  'chat.list.open': 'Open “{title}”',
  'chat.list.actions': 'Actions for “{title}”',
  'chat.list.local_note': 'History isn’t saved by the manager yet. Conversations are kept in this browser only.',
  'chat.list.local_title': 'Saved in this browser.',
  'chat.list.couldnt_save': 'Couldn’t save the conversation.',
  'chat.list.storage_full': 'This browser’s storage is full; older conversations may not be kept.',

  // delete (07 §3.4)
  'chat.delete.title': 'Delete chat.',
  'chat.delete.summary': '{title} · {messages} · {attachments}',
  'chat.delete.messages.one': '{n} message',
  'chat.delete.messages.other': '{n} messages',
  'chat.delete.attachments.one': '{n} attachment ({size})',
  'chat.delete.attachments.other': '{n} attachments ({size})',
  'chat.delete.no_attachments': 'no attachments',
  'chat.delete.confirm': 'Delete · {size}',
  'chat.delete.confirm_plain': 'Delete chat',
  'chat.delete.streaming': 'This conversation is streaming; deleting it stops the reply first.',
  'chat.delete.done': 'Deleted “{title}”.',
  'chat.delete.failed': 'Couldn’t delete the conversation.',
  'chat.rename.failed': 'Couldn’t rename the conversation.',
  'chat.export.done': 'Exported “{title}”.',

  // empty states (07 §3.6)
  'chat.empty.statement': 'Say something.',
  'chat.empty.line': 'Messages stay on this Mac in ~/.splash/chats.',
  'chat.empty.line_local': 'Messages stay in this browser until the manager can save chats.',
  'chat.empty.no_models': 'No models installed. Download one from Models → Downloader.',
  'chat.empty.open_downloader': 'Open downloader',
  'chat.load_chats': 'conversations',
  'chat.load_chat': 'this conversation',
  'chat.not_found': 'This conversation no longer exists.',

  // model selector (07 §4)
  'chat.model.label': 'Model',
  'chat.model.choose': 'Choose a model',
  'chat.model.none': 'No model',
  'chat.model.menu_label': 'Model and profile: {value}',
  'chat.model.group.active': 'Active',
  'chat.model.group.installed': 'Installed',
  'chat.model.group.stopped': 'Not loaded (engine stopped)',
  'chat.model.profile_item': ': {profile}',
  'chat.model.alias': 'alias: {names}',
  'chat.stats.ctx': 'CTX',
  'chat.stats.pp': 'PP',
  'chat.stats.tg': 'TG',
  'chat.stats.ttft': 'TTFT',
  'chat.stats.tip.ctx': 'Context used: {used} of {total} tokens',
  'chat.stats.tip.ctx_est': 'Context used: {used} of about {total} tokens (the window is estimated)',
  'chat.stats.tip.pp': 'Prompt processing speed (prefill): live while a reply runs, then the last reply\'s',
  'chat.stats.tip.tg': 'Token generation speed (decode): live while a reply runs, then the last reply\'s',
  'chat.stats.tip.ttft': 'Time to first token of the last reply, measured here from send',
  'chat.model.ctx': '{ctx} ctx',
  'chat.model.ctx_est': '≈{ctx} ctx',
  'chat.model.vision': 'Vision',
  'chat.model.text_only': 'Text only',
  'chat.model.will_switch': 'Will switch from {active} (≈{s} s)',
  'chat.model.stopped': 'Stopped · starts on send',
  'chat.model.not_loaded': 'Not loaded',
  'chat.model.load_now': 'Load now',
  'chat.model.loading_failed': 'Couldn’t load the model.',
  'chat.model.load_models_failed': 'the model list',

  // messages (07 §5)
  'chat.role.user': 'You',
  'chat.role.assistant': 'Assistant',
  'chat.role.system': 'System',
  'chat.role.tool': 'Tool',
  'chat.msg.copy': 'Copy',
  'chat.msg.copy_text': 'Text',
  'chat.msg.copy_md': 'Markdown',
  'chat.msg.copy_thinking': 'With thinking',
  'chat.msg.copied': 'Copied.',
  'chat.msg.regenerate': 'Regenerate',
  'chat.msg.edit': 'Edit',
  'chat.msg.delete_branch': 'Delete branch',
  'chat.msg.delete_confirm.one': 'Delete this message and {n} reply?',
  'chat.msg.delete_confirm.other': 'Delete this message and {n} replies?',
  'chat.msg.delete_confirm_single': 'Delete this message?',
  'chat.msg.resend': 'Resend',
  'chat.msg.save': 'Save',
  'chat.msg.edit_label': 'Edit message',
  'chat.msg.branch_prev': 'Previous branch',
  'chat.msg.branch_next': 'Next branch',
  'chat.msg.branch_count': '{i} / {n}',
  'chat.msg.branch_label': 'Branch {i} of {n}',
  'chat.msg.actions': 'Message actions',

  // meta line (07 §5.7)
  'chat.meta.in': 'In {n}',
  'chat.meta.in_cached': 'In {n} ({c} cached)',
  'chat.meta.out': 'Out {n}',
  'chat.meta.out_est': '≈ {n} out',
  'chat.meta.ttft': 'TTFT {v}',
  'chat.meta.tokps': '{v}',
  'chat.meta.finish.stop': 'Stop',
  'chat.meta.finish.length': 'Length',
  'chat.meta.finish.tool_calls': 'Tool calls',
  'chat.meta.finish.stopped': 'Stopped',
  'chat.meta.finish.error': 'Error',
  'chat.meta.finish.disconnected': 'Disconnected',
  'chat.meta.tip.in': 'usage.prompt_tokens = {n}; prompt_tokens_details.cached_tokens = {c}',
  'chat.meta.tip.out': 'usage.completion_tokens = {n}',
  'chat.meta.tip.out_est': 'Usage unknown after Stop; estimated from the streamed text (characters ÷ 4).',
  'chat.meta.tip.ttft': 'Measured here from send to the first token · timings.prompt_ms = {ms}',
  'chat.meta.tip.tokps': 'timings.predicted_per_second = {v}',
  'chat.meta.tip.finish': 'finish_reason = {v}',
  'chat.meta.tip.profile': 'Profile {v} (model {id}:{v})',
  'chat.meta.injected.one': '+{n} default',
  'chat.meta.injected.other': '+{n} defaults',

  // thinking (07 §5.4)
  'chat.thinking.label': 'Thinking',
  'chat.thinking.elapsed': '{s} s',
  'chat.thinking.tokens': '{n} tokens',
  'chat.thinking.tokens_pending': '… tokens',

  // tool calls (07 §5.5, §9.3)
  'chat.tool.call': 'Tool call',
  'chat.tool.arguments': 'Arguments',
  'chat.tool.invalid_args': 'Arguments are not valid JSON',
  'chat.tool.result': 'Result',
  'chat.tool.pending': 'Pending',
  'chat.tool.manual': 'Manual',
  'chat.tool.mcp': 'MCP {server}',
  'chat.tool.auto_allowed': 'Auto-allowed',
  'chat.tool.error': 'Error',
  'chat.tool.skipped': 'Skipped',
  'chat.tool.unknown': 'Unknown tool',
  'chat.tool.result_placeholder': 'Type the tool’s result (text/JSON)…',
  'chat.tool.result_label': 'Result for {name}',
  'chat.tool.submit': 'Submit result',
  'chat.tool.skip': 'Skip',
  'chat.tool.skip_text': 'skipped by user',
  'chat.tool.edit_result': 'Change',
  'chat.tool.confirm_q': 'Run {tool} on {server} with these arguments?',
  'chat.tool.run': 'Run',
  'chat.tool.run_always': 'Run and always allow for this server',
  'chat.tool.running': 'Running',
  'chat.tool.waiting.one': 'Waiting for {n} tool result',
  'chat.tool.waiting.other': 'Waiting for {n} tool results',
  'chat.tool.send_all': 'Send all',
  'chat.tool.unknown_prefill': '{"error":"unknown tool"}',
  'chat.tool.mcp_failed': 'The MCP call failed.',
  'chat.tool.allow_failed': 'Couldn’t turn on Always allow for {server}.',

  // prefill (07 §6)
  'chat.progress.reading': 'Reading prompt {p} / {t}',
  'chat.progress.reading_cached': 'Reading prompt {p} / {t} ({c} cached)',
  'chat.progress.waiting': 'Waiting for the engine',
  'chat.progress.loading': 'Loading weights',
  'chat.progress.queued': 'Queued',
  'chat.progress.label': 'Prompt progress',

  // composer (07 §7)
  'chat.composer.label': 'Message',
  'chat.composer.placeholder': 'Message {name}…',
  'chat.composer.placeholder_plain': 'Message…',
  'chat.composer.send': 'Send',
  'chat.composer.stop': 'Stop',
  'chat.composer.attach': 'Attach',
  'chat.composer.hint': 'Enter ↵ send · Shift+Enter newline',
  'chat.composer.counter.one': '{n} attachment · {used} / 64 MiB',
  'chat.composer.counter.other': '{n} attachments · {used} / 64 MiB',
  'chat.composer.drop': 'Drop images or PDFs',
  'chat.composer.drop_text_only': 'This model is text only',
  'chat.composer.vision_off': 'Model loaded with language-only',
  'chat.composer.paste_ignored': 'Images are off for this model (language-only).',
  'chat.composer.fix_panel': 'Fix the Sampling panel first.',
  'chat.composer.fix_tools': 'Fix the Tools panel first.',
  'chat.composer.fix_output': 'Fix the Output panel first.',
  'chat.composer.fix_attachments': 'Remove attachments over the limit first.',
  'chat.composer.remove_attachment': 'Remove {name}',
  'chat.composer.unsupported_file': '{name} isn’t an image or a PDF.',
  'chat.composer.read_failed': 'Couldn’t read {name}.',
  'chat.composer.edit_cancel': 'Cancel',
  'chat.composer.editing': 'Editing a message. Resend makes a new branch.',
  'chat.composer.disabled_no_model': 'Choose a model first.',
  'chat.composer.disabled_load': 'Load the model first.',

  // attachments (07 §7.3)
  'chat.att.pages': '{n} pages',
  'chat.att.page': '1 page',
  'chat.att.pages_unknown': '? pages',
  'chat.att.resize': 'Will be resized',
  'chat.att.too_many_pages': 'Too many pages: {n} of 64.',
  'chat.att.too_big': 'Attachments are {size} MiB; the limit is 64 MiB.',
  'chat.att.image': 'Image {name}',
  'chat.att.open': 'Open {name}',

  // side panel (07 §9)
  'chat.panel.label': 'Request settings',
  'chat.panel.tabs': 'Panel sections',
  'chat.panel.tab.sampling': 'Sampling',
  'chat.panel.tab.system': 'System',
  'chat.panel.tab.tools': 'Tools',
  'chat.panel.tab.output': 'Output',
  'chat.panel.tab_attention': '{tab} (needs attention)',

  'chat.source.model_default': 'Model default',
  'chat.source.profile': 'Profile',
  'chat.source.set_here': 'Set here',
  'chat.source.splash_default': 'Splash default',
  'chat.field.clear': 'Clear {label} back to the model default',

  'chat.sampling.profile': 'Profile',
  'chat.sampling.profile_help': 'Overlays the model’s defaults for this chat. Same as picking model:profile.',
  'chat.sampling.edit_profiles': 'Edit profiles ↗',
  'chat.sampling.reset': 'Reset to model defaults',
  'chat.sampling.undo_reset': 'Undo reset',
  'chat.sampling.model_default': 'Model default',
  'chat.sampling.reasoning_effort': 'Reasoning effort',
  'chat.sampling.temperature': 'Temperature',
  'chat.sampling.top_p': 'Top P',
  'chat.sampling.top_k': 'Top K',
  'chat.sampling.min_p': 'Min P',
  'chat.sampling.presence_penalty': 'Presence penalty',
  'chat.sampling.frequency_penalty': 'Frequency penalty',
  'chat.sampling.repetition_penalty': 'Repetition penalty',
  'chat.sampling.seed': 'Seed',
  'chat.sampling.max_tokens': 'Max tokens',
  'chat.sampling.stop': 'Stop sequences',
  'chat.sampling.priority': 'Priority',
  'chat.sampling.timeout': 'Timeout',
  'chat.sampling.ignore_eos': 'Ignore EOS',
  'chat.sampling.kwargs': 'Template kwargs',
  'chat.sampling.kwargs_format': 'Format',
  'chat.sampling.kwargs_template': '{ "enable_thinking": false }',
  'chat.sampling.priority.normal': 'normal (default)',
  'chat.sampling.priority.foreground': 'foreground',
  'chat.sampling.priority.background': 'background',
  'chat.sampling.stop_placeholder': 'Type and press Enter',
  'chat.sampling.ignore_eos_disabled': 'Not allowed with tools or a response schema',

  'chat.help.temperature': 'Higher is more random. Splash default 1.0.',
  'chat.help.top_p': 'Nucleus sampling cut-off. Splash default 0.95.',
  'chat.help.top_k': 'Splash default 20. 0 or −1 means no limit.',
  'chat.help.min_p': 'Splash default 0.',
  'chat.help.penalty': 'Splash default 0.',
  'chat.help.repetition': 'Splash default 1 (off).',
  'chat.help.seed': 'Same seed, same settings, same answer — with temperature 0.',
  'chat.help.max_tokens': 'Leave empty to let the model decide.',
  'chat.help.stop': 'Up to 4, as Splash allows.',
  'chat.help.priority': 'Foreground requests go first; background ones yield.',
  'chat.help.timeout': 'Seconds. Shorter than the server’s request timeout only.',
  'chat.help.ignore_eos': 'Keep generating past the end-of-sequence token.',
  'chat.help.kwargs': 'Passed to the chat template; Chat only.',
  'chat.help.reasoning_effort': 'Model default sends nothing.',

  'chat.err.temperature': 'Temperature must be between 0 and 2.',
  'chat.err.top_p': 'Top P must be between 0 and 1.',
  'chat.err.top_k': 'Top K must be 0, −1 or a positive integer.',
  'chat.err.min_p': 'Min P must be between 0 and 1.',
  'chat.err.presence_penalty': 'Presence penalty must be between −2 and 2.',
  'chat.err.frequency_penalty': 'Frequency penalty must be between −2 and 2.',
  'chat.err.repetition_penalty': 'Repetition penalty must be greater than 0.',
  'chat.err.seed': 'Seed must be a whole number.',
  'chat.err.max_tokens': 'Max tokens must be at least 1.',
  'chat.err.max_tokens_ctx': 'Larger than the model’s context ({n}).',
  'chat.err.stop_count': 'Up to 4 stop sequences.',
  'chat.err.stop_len': 'Each stop sequence is at most 64 characters.',
  'chat.err.timeout': 'Timeout must be a positive number of seconds.',
  'chat.err.kwargs': 'Must be a JSON object, e.g. {"enable_thinking": false}.',

  'chat.system.prompt': 'System prompt',
  'chat.system.prompt_help': 'Sent as the first message of every request in this chat.',
  'chat.system.later': 'Later system messages',
  'chat.system.later_placeholder': 'Instructions to add at this point of the conversation…',
  'chat.system.insert': '+ Insert system message at the end',
  'chat.system.unsupported_title': 'Later system messages are rejected.',
  'chat.system.unsupported':
    'This model’s chat template does not accept system messages after the first one. Splash will reject the request with 400: “{msg}”. Put instructions in the system prompt or in a user message instead.',
  'chat.system.patched': 'Later system messages are supported through Splash’s template patch.',

  'chat.tools.definitions': 'Tool definitions',
  'chat.tools.defined.one': '{n} defined',
  'chat.tools.defined.other': '{n} defined',
  'chat.tools.help': 'An array of OpenAI tool objects: [{"type":"function","function":{…}}].',
  'chat.tools.template': 'Template',
  'chat.tools.template.get_weather': 'get_weather',
  'chat.tools.template.search': 'search',
  'chat.tools.template.run_sql': 'run_sql',
  'chat.tools.template.empty': 'empty',
  'chat.tools.choice': 'Tool choice',
  'chat.tools.choice_named': 'Named tool',
  'chat.tools.choice.auto': 'auto',
  'chat.tools.choice.none': 'none',
  'chat.tools.choice.required': 'required',
  'chat.tools.choice.named': 'named',
  'chat.tools.need_tool': 'Define at least one tool first.',
  'chat.tools.parallel': 'Parallel calls',
  'chat.tools.execution': 'Execution',
  'chat.tools.exec.manual': 'Manual',
  'chat.tools.exec.mcp': 'MCP servers',
  'chat.tools.exec_help.manual': 'Pause and let me type each result.',
  'chat.tools.exec_help.mcp': 'Run tools on connected servers, after a confirmation.',
  'chat.tools.mcp_servers': 'MCP servers',
  'chat.tools.configure': 'Configure ↗',
  'chat.tools.no_servers': 'No MCP servers configured. Add them in Settings → Chat & MCP.',
  'chat.tools.server_tools.one': '{n} tool',
  'chat.tools.server_tools.other': '{n} tools',
  'chat.tools.server_on': 'Use {server} in this chat',
  'chat.tools.always_allow': 'Always allow',
  'chat.tools.always_allow_label': 'Always allow {server}',
  'chat.tools.collision': '{name} is defined here and by MCP server {server}; the MCP tool wins.',
  'chat.tools.load_servers': 'MCP servers',
  'chat.tools.load_tools': 'MCP tools',

  'chat.json.not_array': 'Must be a JSON array of tool objects.',
  'chat.json.tool_type': 'Tool {i}: only "type": "function" tools are supported.',
  'chat.json.tool_name': 'Tool {i}: function.name must be 1–128 letters, digits, _ or -.',
  'chat.json.tool_params': 'Tool {i}: function.parameters must be an object.',
  'chat.json.tool_dup': 'Tool {i}: {name} is defined twice.',
  'chat.json.line': 'Line {line}, column {col}: {msg}',
  'chat.json.invalid': 'Not valid JSON: {msg}',

  'chat.output.format': 'Response format',
  'chat.output.text': 'Text',
  'chat.output.json_object': 'JSON object',
  'chat.output.json_schema': 'JSON schema',
  'chat.output.schema': 'Schema',
  'chat.output.valid': 'Valid ✓',
  'chat.output.invalid': 'Invalid ✗',
  'chat.output.name': 'Name',
  'chat.output.strict': 'Strict',
  'chat.output.help': 'Splash constrains generation to this schema. Ignore EOS is disabled while a schema is on.',
  'chat.output.template': 'Template',
  'chat.output.template.person': 'person',
  'chat.output.template.list': 'list of items',
  'chat.output.template.classification': 'classification',
  'chat.output.schema_object': 'The schema must be a JSON object.',
  'chat.output.schema_type': 'The schema needs a "type".',
  'chat.output.schema_properties': 'An object schema needs "properties".',
  'chat.output.name_invalid': 'Name must be 1–64 letters, digits, _ or -.',
  'chat.output.result_valid': 'Valid ✓',
  'chat.output.result_matches': 'Valid ✓ · matches schema “{name}”',
  'chat.output.result_invalid': 'Invalid ✗ · {reason}',
  'chat.output.reason_parse': 'not valid JSON',
  'chat.output.reason_type': 'expected {type}',
  'chat.output.reason_required': 'missing “{key}”',
  'chat.output.reason_stopped': 'the reply was cut off',

  // errors (07 §10)
  'chat.error.unreachable': 'Splash GUI’s manager isn’t reachable.',
  'chat.error.unreachable_body': 'Chats can’t be saved or sent until it is back.',
  'chat.error.not_loaded': 'No model is loaded.',
  'chat.error.not_loaded_body': 'Load {model} to start chatting.',
  'chat.error.recovering': 'Splash is recovering.',
  'chat.error.not_sent': 'Your message was not sent.',
  'chat.error.failed': 'The engine stopped after repeated failures.',
  'chat.error.capacity': 'This prompt doesn’t fit in memory.',
  'chat.error.capacity_body': 'Shorten the conversation, start a new chat, or raise --max-memory / lower --max-context.',
  'chat.error.resource_timeout': 'Timed out waiting for memory.',
  'chat.error.resource_timeout_body': 'Close memory-heavy apps, or load the model with language-only.',
  'chat.error.request_timeout': 'The request timed out.',
  'chat.error.queue_full': 'Splash’s queue is full.',
  'chat.error.queue_full_body': 'Other clients are using every queue slot.',
  'chat.error.mask_timeout': 'Structured output stalled.',
  'chat.error.mask_timeout_body': 'Splash gave up building the grammar mask; try a simpler schema.',
  'chat.error.later_system': 'This model can’t take a system message mid-conversation.',
  'chat.error.later_system_body': 'Move it into the system prompt.',
  'chat.error.rejected': 'Splash rejected the request.',
  'chat.error.ignore_eos': 'Ignore EOS can’t be combined with tools or a schema.',
  'chat.error.not_found': '{model} isn’t installed any more.',
  'chat.error.not_found_body': 'Pick another model.',
  'chat.error.busy': 'Splash is busy serving {model}.',
  'chat.error.busy_body': 'Switching models is disabled while requests are in flight.',
  'chat.error.disconnected': 'The connection dropped while streaming.',
  'chat.error.attachment': 'Splash refused the attachment.',
  'chat.error.midstream': 'The reply failed while streaming.',
  'chat.error.generic': 'The request failed.',

  'chat.action.retry': 'Retry',
  'chat.action.retry_in': 'Retry in {s} s',
  'chat.action.switch_idle': 'Switch when idle',
  'chat.action.load': 'Load model',
  'chat.action.restart': 'Restart engine',
  'chat.action.logs': 'Open logs',
  'chat.action.new_from_here': 'New chat from here',
  'chat.action.memory': 'Open memory settings',
  'chat.action.requests': 'Open request settings',
  'chat.action.output': 'Open output',
  'chat.action.system': 'Open system',
  'chat.action.show_request': 'Show request',
  'chat.action.turn_off_eos': 'Turn off Ignore EOS',
  'chat.action.pick_model': 'Pick a model',
  'chat.action.cancel': 'Cancel',
  'chat.action.dismiss': 'Dismiss',
  'chat.action.regenerate': 'Regenerate',
  'chat.action.remove_attachments': 'Remove attachments',
  'chat.request_sheet': 'Request.',
  'chat.restart_failed': 'Couldn’t restart the engine.',
} as const;

export const t = makeT({ ...en, ...chatStrings });
