/** Downloader strings (docs/ui/03 §3). Keys start with "downloader.". Kept apart from ./models so
 * the Status route (which reads the installed list) does not carry them (SPEC §18.6). */
import { en } from './en';
import { makeT } from './index';
import { modelsStrings } from './models';

export const downloaderStrings = {
  // Downloader (docs/ui/03 §3)
  "downloader.title": "Downloader.",
  "downloader.page_title": "Downloader",
  "downloader.mac": "This Mac: {chip} · {ram} · {free} free",
  "downloader.token": "HF token: {state}",
  "downloader.token.hf_login": "hf login ({user}) ✓",
  "downloader.token.override": "override ({user}) ✓",
  "downloader.token.env": "HF_TOKEN ({user}) ✓",
  "downloader.token.none": "no token · gated repos unavailable",
  "downloader.token_settings": "Hugging Face settings",
  "downloader.tabs": "Downloader view",
  "downloader.tab.supported": "Supported",
  "downloader.tab.id": "Download by ID",
  "downloader.tab.search": "Search Hugging Face",
  "downloader.recommended": "Recommended for this Mac",
  "downloader.installed": "Installed",
  "downloader.needs": "needs ≈ {size}",
  "downloader.vision": "vision",
  "downloader.text_only": "text only",
  "downloader.variants.one": "{n} variant",
  "downloader.variants.other": "{n} variants",
  "downloader.recommended_variant": "recommended {name}",
  "downloader.download": "Download",
  "downloader.download_variant": "Download {name}",
  "downloader.details": "Details",
  "downloader.load": "Load",
  "downloader.estimate": "Memory need is an estimate: weights + draft (~0.5–0.9 GB) + vision (~0.9 GB) + KV runway (~0.5 GB) + 2 GB reserve. Splash’s own startup check decides.",
  "downloader.offline": "Hugging Face is unreachable; showing the catalog from the last refresh.",
  "downloader.thing_catalog": "the supported catalog",
  "downloader.id_label": "Model ID",
  "downloader.id_help": "OWNER/REPO[:VARIANT] — full Hugging Face IDs only.",
  "downloader.check": "Check",
  "downloader.checking": "Checking {id}…",
  "downloader.thing_inspect": "the compatibility check",
  "downloader.summary": "{family} · {format}",
  "downloader.vision_line": "vision: {v}",
  "downloader.draft_line": "draft: {v}",
  "downloader.no_vision": "No usable vision projector: {reason}",
  "downloader.variant": "Variant",
  "downloader.options": "Options",
  "downloader.revision": "Revision",
  "downloader.draft_override": "Draft override",
  "downloader.language_only": "Language-only",
  "downloader.legacy_disabled": "Not available for legacy Splash packages.",
  "downloader.size": "Size {size}",
  "downloader.size_free": "{size} · {free} free",
  "downloader.download_size": "Download · {size}",
  "downloader.no_space": "Not enough space: needs {need} including a 2 GB margin, {free} free. Free space or change the models directory.",
  "downloader.text_forced": "Downloads with language-only on: no usable vision projector.",
  "downloader.search": "Search Hugging Face",
  "downloader.search_placeholder": "qwen3.8",
  "downloader.sort": "Sort",
  "downloader.sort.downloads": "Downloads",
  "downloader.sort.likes": "Likes",
  "downloader.sort.recent": "Recent",
  "downloader.format": "Format",
  "downloader.format.all": "All",
  "downloader.format.mlx": "MLX",
  "downloader.format.gguf": "GGUF",
  "downloader.results.one": "{n} result",
  "downloader.results.other": "{n} results",
  "downloader.lazy_note": "Compatibility is checked as rows scroll into view.",
  "downloader.no_results": "No results for “{q}”.",
  "downloader.no_results_body": "Try the repo name without the owner, or paste a full ID into Download by ID.",
  "downloader.hub_down": "Hugging Face is unreachable.",
  "downloader.offline_link": "Work offline with installed models",
  "downloader.downloads_n": "{n} downloads",
  "downloader.updated": "updated {when}",
  "downloader.hf": "Hugging Face",

} as const;

export const t = makeT({ ...en, ...modelsStrings, ...downloaderStrings });
