/** Common and shell strings (docs/ui/00 §8, 01). Page areas add their own modules next to this one. */
import { makeT } from './index';

export const en = {
  // common verbs and states
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.save': 'Save',
  'common.saving': 'Saving…',
  'common.discard': 'Discard',
  'common.delete': 'Delete',
  'common.deleting': 'Deleting…',
  'common.retry': 'Retry',
  'common.reload': 'Reload',
  'common.back': 'Back',
  'common.clear': 'Clear',
  'common.search': 'Search',
  'common.loading': 'Loading',
  'common.none': 'None',
  'common.on': 'On',
  'common.off': 'Off',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.more': 'More',
  'common.show': 'Show',
  'common.hide': 'Hide',
  'common.download': 'Download',
  'common.reveal': 'Reveal in Finder',
  'common.open': 'Open',
  'common.edit': 'Edit',
  'common.apply': 'Apply',
  'common.reset': 'Reset',
  'common.wrap': 'Wrap',
  'common.nowrap': 'No wrap',
  'common.follow': 'Follow',
  'common.paused': 'Paused',
  'common.stale': 'stale · {age}',
  'common.last_updated': 'last updated {time}',
  'common.unknown': 'Unknown',
  'common.not_available': 'Not available',
  'common.typed_confirm': 'Type {word} to confirm',
  'common.couldnt_load': 'Couldn’t load {thing}.',
  'common.not_implemented': 'This part of Splashboard is not built into the manager yet.',

  // nav and shell
  'nav.main': 'Main',
  'nav.status': 'Status',
  'nav.models': 'Models',
  'nav.chat': 'Chat',
  'nav.tools': 'Tools',
  'nav.integrations': 'Integrations',
  'nav.logs': 'Logs',
  'nav.settings': 'Settings',
  'nav.tab.live': 'Live',
  'nav.tab.history': 'Usage history',
  'nav.tab.manager': 'Manager',
  'nav.tab.downloader': 'Downloader',
  'nav.tab.tail': 'Live tail',
  'nav.tab.diagnostics': 'Diagnostics',
  'nav.tab.playground': 'Playground',
  'nav.tab.tokenizer': 'Tokenizer',
  'nav.tab.judgments': 'Judgments',
  'nav.tab.benchmark': 'Benchmark',
  'nav.logout': 'Log out',
  'nav.engine': 'Splash {version}',
  'nav.engine_unknown': 'Splash —',
  'nav.engine_missing': 'Splash not installed',
  'nav.no_model': 'No model',
  'nav.theme_dark': '☾ Dark',
  'nav.theme_light': '☀ Light',
  'nav.theme_to_dark': 'Switch to dark theme',
  'nav.theme_to_light': 'Switch to light theme',
  'shell.skip': 'Skip to content',
  'shell.title': '{page} — Splashboard',
  'shell.title_bare': 'Splashboard',
  'shell.connected': 'Connected to Splashboard.',
  'shell.offline.title': 'Splashboard is not running.',
  'shell.offline.starting': 'Starting Splashboard…',
  'shell.offline.body': 'Start it from the menu bar icon, or run {cmd} in a terminal. This page reconnects by itself.',
  'shell.offline.lan': 'If you changed the bind address or port, open the new URL.',
  'shell.offline.retry_in': 'Retrying in {s} s',
  'shell.offline.retrying': 'Retrying…',
  'shell.offline.last_seen': 'Last seen',
  'shell.offline.page_title': 'Not running',
  'shell.settings_offline': 'Splashboard is not running. Your changes are kept until it is back.',
  'shell.action_failed': '{action} failed: {why}',
  'shell.shortcuts.title': 'Keyboard shortcuts.',
  'shell.shortcuts.goto': 'Go to {page}',
  'shell.shortcuts.search': 'Focus the page search',
  'shell.shortcuts.help': 'Show this list',
  'shell.shortcuts.escape': 'Close a sheet, menu or toast',
  'shell.shortcuts.theme': 'Toggle the theme',
  'shell.shortcuts.submit': 'Submit the current form',
  'shell.shortcuts.window': 'Status: cycle the chart window',
  'shell.shortcuts.history': 'Status → Usage history',
  'shell.shortcuts.downloader': 'Models → Downloader',

  // alert band
  'alert.critical': 'Critical',
  'alert.warn': 'Warning',
  'alert.info': 'Notice',
  'alert.dismiss': 'Dismiss',
  'alert.dismiss_label': 'Dismiss: {message}',
  'alert.more': '+{n} more ▾',
  'alert.fewer': 'Show fewer ▴',
  'alert.recur': '×{n} · last {time}',
  'alert.recur_help': 'First at {time} · notifications at most every 10 min',

  // engine state chips (docs/ui/00 §5.1)
  'state.offline': 'Offline',
  'state.stopped': 'Stopped',
  'state.preparing': 'Preparing',
  'state.loading': 'Loading',
  'state.ready': 'Ready',
  'state.generating': 'Generating',
  'state.idle': 'Idle',
  'state.recovering': 'Recovering',
  'state.failed': 'Failed',
  'state.stopping': 'Stopping',
  'state.restarting': 'Restarting',

  // not found
  'notfound.title': 'Not found.',
  'notfound.body': 'There is nothing at {path}.',

  // errors (headline in plain English, API text verbatim after it)
  'error.generic': 'Something went wrong.',
  'error.network': 'Cannot reach Splashboard. Is the manager running?',
  'error.page_load': 'This page failed to load. Splashboard may have been updated; reload the page.',
  'error.engine_unavailable': 'The engine is not running.',

  // confirm sheet
  'confirm.typed_label': 'Type {word} to confirm',
  'confirm.word.delete': 'DELETE',
  'confirm.word.clear': 'CLEAR',
} as const;

export type CommonKey = keyof typeof en;
export const t = makeT(en);
