/** Integrations strings (docs/ui/09). Keys start with "integrations.". Common keys come from ./en. */
import { en } from './en';
import { makeT } from './index';

export const integrationsStrings = {
  'integrations.page_title': 'Integrations',
  'integrations.title': 'Integrations.',
  'integrations.lead': 'Session-only: splash launch configures a client for one run. Plain claude, codex, … stay exactly as they were.',
  'integrations.server_label': 'Server',
  'integrations.key_on': 'Key on',
  'integrations.key_off': 'Key off',
  'integrations.model': 'Model',
  'integrations.model_aria': 'Model for every command and snippet on this page',
  'integrations.model_active': '{id} (active)',
  'integrations.model_none': 'No model yet',
  'integrations.thing': 'integrations',
  'integrations.mac_only': 'Only from the Mac running Splash GUI',

  // unclean shutdown (§6)
  'integrations.unclean.title': 'Splash GUI didn’t shut down cleanly while a desktop app was connected.',
  'integrations.unclean.body': 'The app may still be pointing at Splash. Reconnect it or restore its own configuration.',
  'integrations.unclean.reconnect': 'Reconnect',
  'integrations.unclean.restore': 'Restore now',
  'integrations.unclean.restore_all': 'Restore all apps',

  // CLI agents (§3)
  'integrations.cli': 'CLI agents',
  'integrations.cli.installed': 'Installed {version}',
  'integrations.cli.installed_unknown': 'Installed · version unknown',
  'integrations.cli.not_installed': 'Not installed',
  'integrations.cli.install': 'Install',
  'integrations.cli.last_launched': 'Last launched {when}',
  'integrations.cli.will_load': 'Will load {model} first',
  'integrations.cli.open_terminal': 'Open in Terminal',
  'integrations.cli.opened': 'Opened',
  'integrations.cli.terminal_failed': 'Couldn’t open Terminal.',
  'integrations.cli.terminal_failed_body': 'macOS blocked Automation for Splash GUI. Allow it in System Settings → Privacy & Security → Automation, or copy the command instead.',
  'integrations.cli.command_aria': 'Command for {name}',
  'integrations.cli.changes': 'What this changes',
  'integrations.cli.summary.claude': 'Environment for this session only. Nothing is written to disk.',
  'integrations.cli.summary.codex': '-c overrides for this session only.',
  'integrations.cli.summary.opencode': 'An inline config in OPENCODE_CONFIG_CONTENT; OpenCode 2 runs with --standalone so the config stays private to this session.',
  'integrations.cli.summary.hermes': 'A dedicated Hermes profile named splash (or splash-<port>). Your default profile is untouched.',
  'integrations.cli.summary.pi': 'One provider entry in ~/.pi/agent/models.json. Pi’s default provider is unchanged.',
  'integrations.cli.profiles': 'Profiles',
  'integrations.cli.profiles.claude': 'Reasoning effort passed as --effort; :no-think as MAX_THINKING_TOKENS=0.',
  'integrations.cli.profiles.codex': 'Reasoning effort passed as -c model_reasoning_effort.',
  'integrations.cli.profiles.opencode': 'Honoured, :no-think included.',
  'integrations.cli.profiles.hermes': 'Reasoning effort passed as --reasoning.',
  'integrations.cli.profiles.pi': 'Reasoning effort passed as --thinking; :no-think as off.',
  'integrations.cli.env': 'Environment',
  'integrations.cli.args': 'Arguments',
  'integrations.cli.files': 'Files',
  'integrations.cli.notes': 'Notes',
  'integrations.cli.backups': 'Backups',
  'integrations.cli.changes_thing': 'what this changes',
  'integrations.cli.static': 'Static description',
  'integrations.cli.secret': 'key hidden',
  'integrations.cli.removed_env': 'Removed',
  'integrations.cli.command': 'Command',
  'integrations.backup_view': 'View backup',
  'integrations.backup_none': 'No backup yet.',
  'integrations.backup_failed': 'Couldn’t reveal the backup.',
  'integrations.cli.source': 'Source: Splash install/clients.py. Splash GUI only sets SPLASH_PORT, the model argument with a profile, and for Codex -c features.apps=false.',
  'integrations.cli.profile_note': 'Profiles through {name} are passed as --model; if this version ignores it, the session uses the base model and the CLI prints a notice.',
  'integrations.cli.entry_hermes': 'Profile {entry} present',
  'integrations.cli.entry_pi': 'Provider {entry} present',
  'integrations.cli.remove': 'Remove',
  'integrations.cli.remove_title_hermes': 'Remove Hermes profile.',
  'integrations.cli.remove_title_pi': 'Remove Pi provider.',
  'integrations.cli.remove_body': '{file} · {kind} {entry}',
  'integrations.cli.remove_kind_hermes': 'profile',
  'integrations.cli.remove_kind_pi': 'provider',
  'integrations.cli.remove_backup': 'A backup goes to {dir}.',
  'integrations.cli.removed': 'Removed · backup saved.',
  'integrations.cli.remove_failed': 'Couldn’t remove the entry.',

  // desktop apps (§4)
  'integrations.desktop': 'Desktop apps',
  'integrations.desktop.not_detected': 'Not detected',
  'integrations.desktop.looked': 'Looked in /Applications and ~/Applications.',
  'integrations.desktop.install_first': 'Install the app first',
  'integrations.desktop.detected': 'Detected {version}',
  'integrations.desktop.detected_bare': 'Detected',
  'integrations.desktop.not_connected': 'Not connected',
  'integrations.desktop.connecting': 'Connecting',
  'integrations.desktop.connected_since': 'Connected since {time}',
  'integrations.desktop.connected': 'Connected',
  'integrations.desktop.restoring': 'Restoring',
  'integrations.desktop.needs_restore': 'Needs restore',
  'integrations.desktop.untested': 'Untested version',
  'integrations.desktop.untested_tip': 'This version has not been tested with Splash GUI; newer or older versions may differ.',
  'integrations.desktop.running': 'Running',
  'integrations.desktop.connect': 'Connect',
  'integrations.desktop.disconnect': 'Disconnect',
  'integrations.desktop.open_app': 'Open app',
  'integrations.desktop.open_failed': 'Couldn’t open the app.',
  'integrations.desktop.lead.claude-desktop': 'Routes Claude’s model slots to Splash through a loopback gateway.',
  'integrations.desktop.lead.codex-app': 'Adds Splash models beside your ChatGPT models; everything else still goes to OpenAI.',
  'integrations.desktop.engine_stopped': 'Engine stopped · loads on the app’s next request',
  'integrations.desktop.connect_title': 'Connect {label}.',
  'integrations.desktop.connect_body': '{label} will restart. Your previous configuration is backed up and restored when you disconnect or quit Splash GUI.',
  'integrations.desktop.connect_running': 'Quit, connect and reopen',
  'integrations.desktop.connect_unsaved': 'Unsaved work in {label} will be lost.',
  'integrations.desktop.connect_closed': '{label} will open when you connect.',
  'integrations.desktop.connect_gateway': 'Gateway: http://127.0.0.1:{port} (loopback only).',
  'integrations.desktop.connect_failed': 'Couldn’t connect.',
  'integrations.desktop.disconnect_title': 'Disconnect {label}.',
  'integrations.desktop.disconnect_body': 'Restores the configuration backed up when you connected{since}.',
  'integrations.desktop.disconnect_restart': '{label} will restart if it is running.',
  'integrations.desktop.restored': 'Restored from backup.',
  'integrations.desktop.restore_failed': 'Couldn’t restore.',
  'integrations.desktop.changes': 'What this changes',
  'integrations.desktop.restore_note': 'Restored on Disconnect, Quit, manager shutdown and system shutdown. splash launch claude-desktop --restore also works when the manager isn’t running.',
  'integrations.desktop.codex_note': 'Requests for ChatGPT models still go to chatgpt.com / api.openai.com; only Splash models are served locally.',
  'integrations.desktop.file': 'File',
  'integrations.desktop.change': 'Change',
  'integrations.desktop.restart_needed': 'App restart needed',
  'integrations.desktop.step_failed': 'The last step failed.',
  'integrations.step.quitting_app': 'Quitting the app',
  'integrations.step.backing_up': 'Backing up',
  'integrations.step.starting_gateway': 'Starting the gateway',
  'integrations.step.writing_config': 'Writing config',
  'integrations.step.opening_app': 'Opening the app',
  'integrations.step.restoring_files': 'Restoring files',
  'integrations.step.done': 'Done',
  'integrations.step.failed': 'Failed',
  'integrations.codex_restart': 'Restart Codex',
  'integrations.codex_restart_title': 'Restart Codex.',
  'integrations.codex_restart_body': 'Codex reads its config at launch. Splash GUI restores and reconnects it so the new default applies; Codex quits and reopens. Unsaved work in Codex will be lost.',
  'integrations.codex_restarted': 'Codex restarted with the new default.',
  'integrations.slots.preview': 'Show response',
  'integrations.slots.preview_note': 'What the gateway answers on /v1/models with these slots (saved values apply per request).',
  'integrations.files.claude_config': 'Created: gateway provider on the loopback port, display name “Splash”, chat tab on, deployment chooser off, telemetry off, inferenceModels removed.',
  'integrations.files.claude_meta': 'appliedId and an entry named “Splash”.',
  'integrations.files.claude_mode': 'deploymentMode: "3p".',
  'integrations.files.backups': 'Snapshot and backups, written before any of the above.',
  'integrations.files.codex_config': 'openai_base_url and model_catalog_json point at Splash GUI; desktop.enabled-reasoning-efforts gains none and max; model is set only when “Make Splash the default model” is on.',
  'integrations.files.codex_models': 'Splash entries first, then the app’s native models.',
  'integrations.files.codex_routing': 'Which model IDs route to Splash.',
  'integrations.files.codex_auth': 'Created only if missing, as the sentinel {"OPENAI_API_KEY":"splash-local-codex","auth_mode":"apikey"}.',

  // Claude Desktop slots (§4.4)
  'integrations.slots': 'Model slots',
  'integrations.slots.lead': 'Claude’s pickers and subagents ask for these IDs; each is answered by a Splash model.',
  'integrations.slots.slot': 'Slot',
  'integrations.slots.model': 'Splash model or profile',
  'integrations.slots.active': 'Active model (follows switches)',
  'integrations.slots.autoload': 'Changing a slot to a model that isn’t loaded makes Claude’s next request switch models (auto-load).',
  'integrations.slots.reset': 'Reset all to active model',
  'integrations.slots.saved': 'Saved',
  'integrations.slots.switch_warn': 'Claude may switch models between a main turn and a subagent; each switch takes a few seconds.',
  'integrations.slots.failed': 'Couldn’t save the slots.',

  // Codex default model (§4.6)
  'integrations.codex_default': 'Make Splash the default model in Codex app',
  'integrations.codex_default_help': 'Sets model in ~/.codex/config.toml to the picked Splash model. Off keeps your ChatGPT default and only adds Splash to the picker.',
  'integrations.codex_default_failed': 'Couldn’t change the Codex default.',

  // SDKs & apps (§5)
  'integrations.sdk': 'SDKs & apps',
  'integrations.sdk.tabs': 'SDK',
  'integrations.sdk.openai_py': 'OpenAI Python',
  'integrations.sdk.openai_js': 'OpenAI JS',
  'integrations.sdk.anthropic_py': 'Anthropic Python',
  'integrations.sdk.anthropic_js': 'Anthropic JS',
  'integrations.sdk.typesafe': 'TypeSafe SDK',
  'integrations.sdk.bionic': 'LM Studio Bionic',
  'integrations.sdk.jan': 'Jan / Tauri',
  'integrations.sdk.bionic_body': 'Bionic connects to any OpenAI-compatible server. Use base URL {url} and model {model}.',
  'integrations.sdk.bionic_link': 'LM Studio Bionic guide',
  'integrations.sdk.jan_body': 'Tauri apps call the API from the origin tauri://localhost, which Splash GUI blocks unless allowed.',
  'integrations.sdk.allow_origin': 'Allow origin tauri://localhost',
  'integrations.sdk.allowed': 'Allowed ✓',
  'integrations.sdk.wildcard': 'All origins are already allowed.',
  'integrations.sdk.manage': 'Manage in Settings → Server & network',
  'integrations.sdk.allow_failed': 'Couldn’t allow the origin.',
  'integrations.sdk.allowed_toast': 'Origin tauri://localhost allowed.',
} as const;

export const t = makeT({ ...en, ...integrationsStrings });
