import { en } from "./en";
import { makeT } from "./index";

export const logsStrings = {
  "logs.page_title": "Logs",
  "logs.bundle.engine": "Engine",
  "logs.bundle.engine_missing": "Splash is not installed.",
  "logs.bundle.hardware": "Hardware",
  "logs.bundle.header": "Splash GUI diagnostics · {time}",
  "logs.bundle.log": "Log",
  "logs.bundle.no_command": "No launch command recorded.",
  "logs.bundle.settings": "Settings",
  "logs.bundle.source": "Source",
  "logs.bundle.stopped": "Engine stopped",
  "logs.bundle.unknown": "Not available",
  "logs.bundle.versions": "Versions",
  "logs.clear": "Clear",
  "logs.clear.busy": "Clearing…",
  "logs.clear.confirm": "Clear logs",
  "logs.clear.done": "Logs cleared.",
  "logs.clear.failed": "Could not clear logs.",
  "logs.clear.session": "The current engine session continues.",
  "logs.clear.title": "Clear logs.",
  "logs.clear.what":
    "This clears both engine and manager logs, including rotated files.",
  "logs.divider.copy_what": "Copy what",
  "logs.divider.exit": "Engine exited",
  "logs.divider.start": "Engine session started",
  "logs.divider.stop": "Engine session stopped",
  "logs.download": "Download",
  "logs.download.engine": "Engine",
  "logs.download.manager": "Manager",
  "logs.empty.engine": "Load a model to see its output here.",
  "logs.empty.load": "Open Models",
  "logs.empty.manager": "Manager output will appear here.",
  "logs.empty.title": "No logs yet.",
  "logs.filter": "Filter",
  "logs.filter_label": "Filter log lines",
  "logs.follow": "Follow",
  "logs.following": "Following",
  "logs.level": "Level",
  "logs.level.req": "Request",
  "logs.level_filter.all": "All levels",
  "logs.level_filter.error": "Error",
  "logs.level_filter.info": "Info",
  "logs.level_filter.warn": "Warn",
  "logs.loading": "Loading logs…",
  "logs.match_next": "Match next",
  "logs.match_pos": "{i} of {n}",
  "logs.match_prev": "Match prev",
  "logs.matches": "{n} matches",
  "logs.meta.dropped": "Older lines were removed from this view.",
  "logs.meta.reconnected": "Reconnected to the log stream.",
  "logs.more": "More",
  "logs.new_lines": "{n} new lines",
  "logs.no_match": "No matching lines.",
  "logs.none_at_level": "No lines match this level.",
  "logs.pane.engine": "Engine log",
  "logs.pane.manager": "Manager log",
  "logs.requests": "Requests",
  "logs.requests_label": "Show request lines",
  "logs.search": "Search",
  "logs.show_all": "Show all levels",
  "logs.source": "Source",
  "logs.source.engine": "Engine",
  "logs.source.manager": "Manager",
  "logs.subnav": "Logs",
  "logs.thing": "logs",
  "logs.timestamps": "Timestamps",
  "logs.title": "Logs.",
  "logs.toolbar": "Toolbar",
  "logs.wrap": "Wrap",
  "logs.tag.ready": "Ready",
  "logs.tag.template": "Template",
  "logs.tag.load": "Load",
  "logs.tag.budget": "Budget",
  "logs.tag.ssd": "Ssd",
  "logs.tag.trace": "Trace",
  "logs.level.error": "Error",
  "logs.level.warn": "Warn",
  "logs.level.info": "Info",
  "logs.level.debug": "Debug",
} as const;

export const t = makeT({ ...en, ...logsStrings });
