import { en } from "./en";
import { makeT } from "./index";

export const logsStrings = {
  "logs.page_title": "Logs",
  "logs.bundle.engine": "Engine",
  "logs.bundle.engine_missing": "Splash is not installed.",
  "logs.bundle.hardware": "Hardware",
  "logs.bundle.header": "Splashboard diagnostics · {time}",
  "logs.bundle.log": "Engine log (last {n} lines)",
  "logs.bundle.no_command": "No launch command recorded.",
  "logs.bundle.settings": "Settings",
  "logs.bundle.source": "Source",
  "logs.bundle.stopped": "Engine stopped",
  "logs.bundle.unknown": "Not available",
  "logs.bundle.versions": "Versions",
  "logs.clear": "Clear",
  "logs.clear.busy": "Clearing…",
  "logs.clear.confirm": "Clear logs",
  "logs.clear.done": "Logs cleared · {size} freed.",
  "logs.clear.failed": "Could not clear logs.",
  "logs.clear.session": "The current engine session continues.",
  "logs.clear.title": "Clear logs.",
  "logs.clear.what":
    "This clears both engine and manager logs, including rotated files.",
  "logs.divider.copy_what": "Copy what",
  "logs.divider.exit": "exit {code}",
  "logs.divider.start": "Engine session started",
  "logs.divider.stop": "Engine session stopped",
  "logs.download": "Download",
  "logs.download.engine": "Engine",
  "logs.download.manager": "Manager",
  "logs.empty.engine": "Load a model to see its output here.",
  "logs.empty.load": "Open Models",
  "logs.empty.manager": "Manager output will appear here.",
  "logs.empty.title": "No logs yet.",
  "logs.filter": "Filter",
  "logs.filter_label": "Filter log lines",
  "logs.follow": "Follow",
  "logs.following": "Following",
  "logs.level": "Level",
  "logs.level.req": "Request",
  "logs.level_filter.all": "All levels",
  "logs.level_filter.error": "Error",
  "logs.level_filter.info": "Info",
  "logs.level_filter.warn": "Warn",
  "logs.loading": "Loading logs…",
  "logs.match_next": "Match next",
  "logs.match_pos": "{i} of {n}",
  "logs.match_prev": "Match prev",
  "logs.matches": "{n} matches",
  "logs.meta.dropped": "Older lines were removed from this view.",
  "logs.meta.reconnected": "Reconnected to the log stream.",
  "logs.more": "More",
  "logs.new_lines": "{n} new lines",
  "logs.no_match": "No lines match “{q}”.",
  "logs.none_at_level": "No lines match this level.",
  "logs.pane.engine": "Engine log",
  "logs.pane.manager": "Manager log",
  "logs.requests": "Requests",
  "logs.requests_label": "Show request lines",
  "logs.search": "Search",
  "logs.show_all": "Show all levels",
  "logs.source": "Source",
  "logs.source.engine": "Engine",
  "logs.source.manager": "Manager",
  "logs.subnav": "Logs",
  "logs.thing": "logs",
  "logs.timestamps": "Timestamps",
  "logs.title": "Logs.",
  "logs.toolbar": "Toolbar",
  "logs.wrap": "Wrap",
  "logs.tag.ready": "Ready",
  "logs.tag.template": "Template",
  "logs.tag.load": "Load",
  "logs.tag.budget": "Budget",
  "logs.tag.ssd": "Ssd",
  "logs.tag.trace": "Trace",
  "logs.level.error": "Error",
  "logs.level.warn": "Warn",
  "logs.level.info": "Info",
  "logs.level.debug": "Debug",
  // Diagnostics
  "logs.diag.title": "Diagnostics.",
  "logs.diag.page_title": "Diagnostics",
  "logs.diag.meta_engine": "Splash {version}",
  "logs.diag.meta_schema": "schema {schema}",
  "logs.diag.meta_gui": "GUI {version}",
  "logs.diag.bundle": "Diagnostic bundle",
  "logs.diag.bundle_body": "Settings with secrets redacted, versions, hardware, the last 500 engine log lines and /status. Paste it into a Splash issue.",
  "logs.diag.bundle_copy": "Copy bundle",
  "logs.diag.bundle_copied": "Bundle copied · {size}",
  "logs.diag.bundle_download": "Download .txt",
  "logs.diag.bundle_included": "What is included",
  "logs.diag.bundle_redaction": "API keys, Hugging Face tokens, the internal engine key and bearer headers are replaced with [redacted]; chat contents are never included.",
  "logs.diag.bundle_issue": "File a Splash issue",
  "logs.diag.bundle_issue_note": "Splash asks for the Splash version, Mac, macOS and model.",
  "logs.diag.bundle_thing": "the diagnostic bundle",
  "logs.diag.raw": "Raw /status",
  "logs.diag.raw_refresh": "Auto-refresh every 5 s",
  "logs.diag.raw_fetched": "fetched {time} · {size}",
  "logs.diag.raw_expand": "Expand all",
  "logs.diag.raw_collapse": "Collapse all",
  "logs.diag.raw_stopped": "Engine stopped — /status is not available.",
  "logs.diag.raw_last": "Last snapshot {time}",
  "logs.diag.raw_schema": "This Splash reports /status schema {schema}; Splashboard reads schema 6. Some numbers may be missing.",
  "logs.diag.raw_thing": "engine status",
  "logs.diag.traces": "Crash traces",
  "logs.diag.traces_on": "Recording on · {dir} · {n} files · {size} (max 4 / 64 MB)",
  "logs.diag.traces_off": "Recording off — turn it on in Settings → Advanced. Traces can contain private conversation data.",
  "logs.diag.traces_settings": "Advanced settings",
  "logs.diag.traces_thing": "crash traces",
  "logs.diag.traces_file": "File",
  "logs.diag.traces_time": "Time",
  "logs.diag.traces_size": "Size",
  "logs.diag.traces_actions": "Actions",
  "logs.diag.traces_none": "No traces recorded.",
  "logs.diag.traces_footer": "Traces are never included in diagnostic bundles.",
  "logs.diag.replay": "Replay",
  "logs.diag.replay_output": "Replay output",
  "logs.diag.replay_note": "Replay starts a second engine process; stop the running model first if memory is tight.",
  "logs.diag.replay_failed": "Replay failed.",
  "logs.diag.replay_exit": "Exited with code {code}.",
  "logs.diag.replay_stop": "Stop",
  "logs.diag.replay_confirm_title": "Replay while the engine runs.",
  "logs.diag.replay_confirm_body": "Replay loads the model again in a second engine process, which needs as much memory again.",
  "logs.diag.replay_stop_engine": "Stop engine & replay",
  "logs.diag.replay_anyway": "Replay anyway",
  "logs.diag.path.permissions": "Permissions",
  "logs.diag.reveal": "Reveal",
  "logs.diag.reveal_failed": "Couldn’t reveal it in Finder.",
  "logs.diag.delete": "Delete",
  "logs.diag.delete_title": "Delete trace.",
  "logs.diag.delete_body": "{name} · {size} · may contain conversation data.",
  "logs.diag.delete_failed": "Couldn’t delete the trace.",
  "logs.diag.doctor": "Doctor",
  "logs.diag.doctor_run": "Run doctor",
  "logs.diag.doctor_thing": "the doctor report",
  "logs.diag.paths": "Paths",
  "logs.diag.paths_thing": "storage paths",
  "logs.diag.path.data": "Splash engine data",
  "logs.diag.path.gui": "Splashboard data",
  "logs.diag.path.models": "Models",
  "logs.diag.path.cache": "Cache",
  "logs.diag.path.logs": "Logs",
} as const;

export const t = makeT({ ...en, ...logsStrings });
