import { en } from "./en";
import { makeT } from "./index";

export const modelsStrings = {
  "models.page_title": "Models",
  "models.action.delete_label": "Delete {id}",
  "models.action.download_variant": "Download {variant}",
  "models.action.download_variant_size": "Download {variant} · {size}",
  "models.action.variant": "Variant",
  "models.action.hf": "View on Hugging Face",
  "models.action.load": "Load",
  "models.action.load_label": "Load {id}",
  "models.action.reveal": "Reveal",
  "models.action.reveal_label": "Reveal {id} in Finder",
  "models.action.settings": "Settings",
  "models.action.settings_label": "Settings for {id}",
  "models.action.unload": "Unload",
  "models.action.unload_label": "Unload {id}",
  "models.action.update": "Update",
  "models.action.update_label": "Update {id}",
  "models.action.verify": "Verify",
  "models.action.verify_label": "Verify {id}",
  "models.byid.checking": "Checking {id}…",
  "models.byid.progress": "{checked} of {total} variants checked. The rest are still being checked.",
  "models.byid.invalid": "Enter a full Hugging Face ID: owner/repo[:variant].",
  "models.byid.short_hint": "Use owner/repo; short names are not supported.",
  "models.cancel.back": "Keep downloading",
  "models.cancel.delete": "Remove downloaded files · {size}",
  "models.cancel.help":
    "Keep completed files and partial downloads for later, or remove what this download added. Files an installed model uses stay.",
  "models.cancel.keep": "Keep files",
  "models.cancel.so_far": "Downloaded so far: {size}",
  "models.cancel.title": "Keep downloaded files for later?",
  "models.catalog.family.dense": "Qwen3.8-27B · Dense",
  "models.catalog.family.moe": "Qwen3.6-35B-A3B · Mixture of experts",
  "models.changed": "Changed",
  "models.clef.body":
    "Splash does not use Clef’s joint schema head. Scores will differ from Cloudflare’s Clef.",
  "models.clef.title": "Clef backbone only.",
  "models.compat.checking": "Checking…",
  "models.compat.compatible": "Compatible",
  "models.compat.error": "Compatibility could not be checked.",
  "models.compat.incompatible": "Incompatible",
  "models.compat.text_only": "Compatible · text only",
  "models.compat.unchecked": "Not checked",
  "models.delete.confirm": "Delete · {size}",
  "models.delete.done_many": "{n} models deleted · {size} freed.",
  "models.delete.done_one": "Deleted {short} · {size} freed.",
  "models.delete.draft_kept": "The shared draft is kept for other models.",
  "models.delete.estimate_note": "Only unshared files are removed.",
  "models.delete.failed": "Could not delete the model: {why}",
  "models.delete.local_keep": "The .gguf file is kept in the models folder.",
  "models.delete.trash_failed": "Could not move {name} to the Trash. It is still in the models folder.",
  "models.delete.trash_label": "Also move the file to the Trash",
  "models.delete.frees": "Frees approximately {size}",
  "models.delete.frees_after": "Frees about {size}: {free} free now, {after} after.",
  "models.delete.now_active": "{short} is now active. Deleting it stops the engine.",
  "models.delete.removes":
    "Removes the selected models and their unshared files.",
  "models.delete.stops_engine": "The active engine will stop before deletion.",
  "models.delete.title_many": "Delete {n} models.",
  "models.delete.title_one": "Delete {short}.",
  "models.delete.unique": "{size} unique",
  "models.disk.cache": "Cache {size}",
  "models.disk.cache_volume": "Cache volume: {free} free of {total}",
  "models.disk.cache_volume_name": "cache volume",
  "models.disk.free": "Free {free} of {total}",
  "models.disk.label": "Disk usage",
  "models.disk.meter": "Disk usage of the {volume}",
  "models.disk.models": "Models {size}",
  "models.disk.models_volume": "models volume",
  "models.disk.seg_cache": "Cache",
  "models.disk.seg_models": "Models",
  "models.disk.splash": "Splash links {size}",
  "models.disk.splash_note":
    "Splash keeps small assembly links in Application Support.",
  "models.disk.storage_settings": "Storage settings",
  "models.disk.thing": "storage information",
  "models.disk.used": "{used} of {total} used",
  "models.disk.volume": "models and cache volume",
  "models.dl.action.add_token": "Add Hugging Face token",
  "models.dl.action.cancel": "Cancel",
  "models.dl.action.details": "Details",
  "models.dl.action.dismiss": "Dismiss",
  "models.dl.action.full_verify": "Verify all files",
  "models.dl.action.pause": "Pause",
  "models.dl.action.redownload": "Redownload",
  "models.dl.action.remove": "Remove",
  "models.dl.action.resume": "Resume",
  "models.dl.action.retry": "Retry",
  "models.dl.action.storage": "Open storage settings",
  "models.dl.action.work_offline": "Work offline",
  "models.dl.cancel_label": "Cancel the download of {model}",
  "models.dl.error.disk_full":
    "Not enough disk space. Need {needed}; {free} available.",
  "models.dl.error.disk_full_plain": "Not enough disk space.",
  "models.dl.error.failed": "Download failed: {message}",
  "models.dl.error.gated":
    "This repository is gated or private. Add a Hugging Face token.",
  "models.dl.error.hub_unreachable":
    "Hugging Face is unreachable. Check the connection and retry.",
  "models.dl.error.incompatible": "Splash’s installer rejected this model: {message}",
  "models.dl.error.interrupted":
    "The download was interrupted. Resume to continue.",
  "models.dl.error.verify_failed": "Verification failed: {message}",
  "models.dl.eta": "{time} remaining",
  "models.dl.file_done": "Done",
  "models.dl.file_pending": "Pending",
  "models.dl.files": "Files ({n})",
  "models.dl.full_verify": "Full file verification",
  "models.dl.history": "Show completed downloads",
  "models.dl.history_hide": "Hide completed downloads",
  "models.dl.idle": "No downloads running",
  "models.dl.item_progress": "Download progress of {model}",
  "models.dl.label": "Downloads",
  "models.dl.last": "Last: {model} · {when}",
  "models.dl.left": "{size} remaining",
  "models.dl.list": "Download queue",
  "models.dl.log": "Installer log",
  "models.dl.log_empty": "Installer output will appear here.",
  "models.dl.log_label": "Installer output for {model}",
  "models.dl.n_active": "{n} active",
  "models.dl.n_paused": "{n} paused",
  "models.dl.n_queued": "{n} queued",
  "models.dl.none": "No downloads yet.",
  "models.dl.of": "{done} of {total}",
  "models.dl.offline_failed": "Could not enable offline mode.",
  "models.dl.offline_on": "Offline mode enabled.",
  "models.dl.overall": "Overall progress",
  "models.dl.overall_text": "{pct} overall",
  "models.dl.parallel": "Parallel downloads",
  "models.dl.parallel_failed": "Could not save the download limit.",
  "models.dl.parallel_saved": "Up to {n} downloads at once.",
  "models.dl.pause_label": "Pause the download of {model}",
  "models.dl.paused_kept": "Paused · {size} kept. Resume continues the download.",
  "models.dl.quick_verify": "Quick verification",
  "models.dl.removed": "Removed from this Mac",
  "models.dl.resume_label": "Resume the download of {model}",
  "models.dl.state.cancelled": "Cancelled",
  "models.dl.state.done": "Done",
  "models.dl.state.failed": "Failed",
  "models.dl.state.paused": "Paused",
  "models.dl.state.queued": "Queued",
  "models.dl.state.running": "Downloading {pct}",
  "models.dl.state.verifying": "Verifying",
  "models.drawer.card": "Card",
  "models.drawer.card_thing": "model card",
  "models.drawer.commit": "Commit",
  "models.drawer.commit_installed": "installed {sha}",
  "models.drawer.commit_latest": "latest {sha}",
  "models.drawer.compat_thing": "compatibility",
  "models.drawer.copy_id": "Copy model ID",
  "models.drawer.draft": "Draft",
  "models.drawer.facts": "Facts",
  "models.drawer.family": "Family",
  "models.drawer.files": "Files ({n})",
  "models.drawer.format": "Format",
  "models.drawer.gated": "Gated or private repository",
  "models.drawer.hf_unreachable": "Could not reach Hugging Face.",
  "models.drawer.last_used": "Last used {when}",
  "models.drawer.legacy_line": "Splash package · Splash no longer loads these",
  "models.drawer.license": "License",
  "models.drawer.mlx_line": "MLX · {n} shards · {size}",
  "models.drawer.no_card": "No model card is available.",
  "models.drawer.tags": "Tags ({n})",
  "models.drawer.template": "Template",
  "models.drawer.template_unknown": "Available after loading the model",
  "models.drawer.title": "{short}.",
  "models.drawer.variants": "Variants",
  "models.drawer.vision": "Vision",
  "models.drawer.vision_no": "Text only",
  "models.drawer.vision_yes": "Vision available",
  "models.drawer.vision_yes_proj": "Vision · {projector}",
  "models.empty.action": "Browse supported models",
  "models.empty.body":
    "Choose a supported model to download and run on this Mac.",
  "models.empty.title": "No models installed.",
  "models.fit.fits": "Fits",
  "models.fit.tight": "Tight",
  "models.fit.tight_help": "Tight on {ram}: reduce the context or use language-only.",
  "models.fit.wont_fit": "Won’t fit",
  "models.fit.wont_help": "Needs about {need}; this Mac has {ram}.",
  "models.format.gguf": "GGUF",
  "models.format.legacy": "Splash package",
  "models.format.mlx": "MLX",
  "models.format.pq2": "PQ2_0",
  "models.format.unknown": "Unknown format",
  "models.local.added": "Added {models}.",
  "models.local.drawer_line": "One GGUF file in the models folder · {size}",
  "models.local.errors": "Files not added",
  "models.local.label": "Local files",
  "models.local.none": "No new .gguf files.",
  "models.local.note": "Drop a .gguf into {dir} and it is added automatically.",
  "models.local.note_default": "the models folder",
  "models.local.rescan": "Rescan folder",
  "models.local.rescan_failed": "Could not rescan the models folder.",
  "models.local.tag": "Local",
  "models.local.tag_title": "Added from a .gguf in the models folder",
  "models.manager.active": "Active",
  "models.manager.count": "{n} installed",
  "models.manager.count_loading": "Loading inventory…",
  "models.manager.downloader": "Downloader",
  "models.manager.free": "{size} free",
  "models.manager.installed": "Installed",
  "models.manager.only_active": "Only the active model is installed.",
  "models.manager.thing": "installed models",
  "models.manager.title": "Models.",
  "models.row.language_only": "Text only",
  "models.row.never_used": "Never loaded",
  "models.row.open_label": "Open details for {id}",
  "models.row.pinned_title": "Pinned to {sha}",
  "models.row.rev": "Revision {rev}",
  "models.row.unique": "{size} unique",
  "models.row.used": "Last used {time}",
  "models.seed.dense_gguf": "Dense model with a choice of GGUF quantizations.",
  "models.seed.dense_mlx":
    "MLX 4-bit · about 21 GB including draft and vision.",
  "models.seed.moe_gguf": "Fast MoE model with GGUF quantization options.",
  "models.seed.moe_mlx": "MLX 4-bit · about 24 GB including draft and vision.",
  "models.seed.pq2": "Prism PQ2_0 · compact dense model with vision.",
  "models.select.delete": "Delete {n} · {size}",
  "models.select.delete_none": "Select models to delete",
  "models.select.row": "Select {id}",
  "models.select.start": "Select models",
  "models.status.broken": "Broken · verify again",
  "models.status.unsupported": "No longer loads",
  "models.status.downloading": "Downloading {pct}",
  "models.status.installed": "Installed",
  "models.status.loading": "Loading",
  "models.status.paused": "Paused",
  "models.status.pinned": "Pinned",
  "models.status.update": "Update available",
  "models.status.verifying": "Verifying",
  "models.stop.body.one": "{n} request in flight will be interrupted.",
  "models.stop.body.other": "{n} requests in flight will be interrupted.",
  "models.stop.title": "Stop the engine.",
  "models.tabs_label": "Models",
  "models.toast.already_queued": "{short} is already queued.",
  "models.toast.busy":
    "The engine is serving requests. Try again when it is idle.",
  "models.toast.download_failed": "Could not download {short}.",
  "models.toast.load_failed": "Could not load {short}.",
  "models.toast.loading": "Loading {model}…",
  "models.toast.pause_failed": "Could not pause.",
  "models.toast.queued": "Queued {model}.",
  "models.toast.queued_size": "Queued {model} · {size}",
  "models.toast.remove_failed": "Could not remove.",
  "models.toast.resume_failed": "Could not resume.",
  "models.toast.reveal_failed": "Could not reveal.",
  "models.toast.stop_failed": "Could not stop.",
  "models.toast.stopping": "Stopping the engine…",
  "models.toast.update_failed": "Could not update {short}.",
  "models.toast.updating": "Updating {model}…",
  "models.toast.verify_failed": "Could not verify {short}.",
  "models.toast.verifying": "Verifying {model}…",
  "models.variant.col.bits": "Bits",
  "models.variant.col.fit": "Fit",
  "models.variant.col.size": "Size",
  "models.variant.col.status": "Status",
  "models.variant.col.tier": "Tier",
  "models.variant.col.variant": "Variant",
  "models.variant.download_label": "Download {name}",
  "models.variant.checking": "Checking…",
  "models.variant.installed": "Installed",
  "models.variant.none": "No variants are available.",
  "models.variant.projector": "Vision projector",
  "models.variant.recommended": "Recommended",
  "models.variant.unsupported": "Unsupported: {reason}",
  "models.variant.unsupported_default":
    "Splash has no kernels for this tensor format.",
  "models.verify.done": "Verified {short}.",
  "models.verify.failed_default":
    "The installer reported a verification error.",
  "models.verify.failed_title": "Verification failed.",
  "models.verify.failed_toast": "Could not verify {short}.",
  "models.file.role.other": "Other",
  "models.file.role.draft": "Draft",
  "models.file.role.weights": "Weights",
  "models.file.role.config": "Config",
  "models.file.role.tokenizer": "Tokenizer",
  "models.file.role.mmproj": "Vision projector",
} as const;

export const t = makeT({ ...en, ...modelsStrings });
