import { en } from "./en";
import { makeT } from "./index";

export const modelsStrings = {
  "models.page_title": "Models",
  "models.action.delete_label": "Delete",
  "models.action.download_variant": "Download variant",
  "models.action.hf": "View on Hugging Face",
  "models.action.load": "Load",
  "models.action.load_label": "Load",
  "models.action.reveal": "Reveal",
  "models.action.reveal_label": "Reveal",
  "models.action.settings": "Settings",
  "models.action.settings_label": "Settings",
  "models.action.unload": "Unload",
  "models.action.unload_label": "Unload",
  "models.action.update": "Update",
  "models.action.update_label": "Update",
  "models.action.verify": "Verify",
  "models.action.verify_label": "Verify",
  "models.byid.checking": "Checking compatibility…",
  "models.byid.invalid": "Enter a full Hugging Face ID: owner/repo[:variant].",
  "models.byid.short_hint": "Use owner/repo; short names are not supported.",
  "models.cancel.back": "Keep downloading",
  "models.cancel.delete": "Remove partial files",
  "models.cancel.help":
    "Keep completed files and partial downloads for later, or remove unused partial files.",
  "models.cancel.keep": "Keep files",
  "models.cancel.so_far": "Downloaded so far: {size}",
  "models.cancel.title": "Cancel download.",
  "models.catalog.family.dense": "Qwen3.8-27B · Dense",
  "models.catalog.family.moe": "Qwen3.6-35B-A3B · Mixture of experts",
  "models.changed": "Changed",
  "models.clef.body":
    "Splash does not use Clef’s joint schema head. Scores will differ from Cloudflare’s Clef.",
  "models.clef.title": "Clef backbone only.",
  "models.compat.checking": "Checking…",
  "models.compat.compatible": "Compatible",
  "models.compat.error": "Compatibility could not be checked.",
  "models.compat.incompatible": "Incompatible",
  "models.compat.text_only": "Compatible · text only",
  "models.compat.unchecked": "Not checked",
  "models.delete.confirm": "Delete models",
  "models.delete.done_many": "{n} models deleted.",
  "models.delete.done_one": "Model deleted.",
  "models.delete.draft_kept": "The shared draft is kept for other models.",
  "models.delete.estimate_note": "Only unshared files are removed.",
  "models.delete.failed": "Could not delete the model.",
  "models.delete.frees": "Frees approximately {size}",
  "models.delete.frees_after": "Freed {size}",
  "models.delete.now_active":
    "This model is now active. Deleting it stops the engine.",
  "models.delete.removes":
    "Removes the selected models and their unshared files.",
  "models.delete.stops_engine": "The active engine will stop before deletion.",
  "models.delete.title_many": "Delete {n} models.",
  "models.delete.title_one": "Delete this model.",
  "models.delete.unique": "Unique",
  "models.disk.cache": "Cache",
  "models.disk.cache_volume": "Cache volume",
  "models.disk.cache_volume_name": "Cache volume name",
  "models.disk.free": "Free",
  "models.disk.label": "Disk usage",
  "models.disk.meter": "Model and cache disk usage",
  "models.disk.models": "Models",
  "models.disk.models_volume": "Models volume",
  "models.disk.seg_cache": "Seg cache",
  "models.disk.seg_models": "Seg models",
  "models.disk.splash": "Splash links and metadata",
  "models.disk.splash_note":
    "Splash keeps small assembly links in Application Support.",
  "models.disk.storage_settings": "Storage settings",
  "models.disk.thing": "storage information",
  "models.disk.used": "Used",
  "models.disk.volume": "Volume",
  "models.dl.action.add_token": "Add Hugging Face token",
  "models.dl.action.cancel": "Cancel",
  "models.dl.action.details": "Details",
  "models.dl.action.dismiss": "Dismiss",
  "models.dl.action.full_verify": "Verify all files",
  "models.dl.action.pause": "Pause",
  "models.dl.action.redownload": "Redownload",
  "models.dl.action.remove": "Remove",
  "models.dl.action.resume": "Resume",
  "models.dl.action.retry": "Retry",
  "models.dl.action.storage": "Open storage settings",
  "models.dl.action.work_offline": "Work offline",
  "models.dl.cancel_label": "Cancel",
  "models.dl.error.disk_full":
    "Not enough disk space. Need {needed}; {free} available.",
  "models.dl.error.disk_full_plain": "Not enough disk space.",
  "models.dl.error.failed": "Download failed.",
  "models.dl.error.gated":
    "This repository is gated or private. Add a Hugging Face token.",
  "models.dl.error.hub_unreachable":
    "Hugging Face is unreachable. Check the connection and retry.",
  "models.dl.error.incompatible": "Splash cannot load this model.",
  "models.dl.error.interrupted":
    "The download was interrupted. Resume to continue.",
  "models.dl.error.verify_failed":
    "Verification failed. Retry or download the files again.",
  "models.dl.eta": "{time} remaining",
  "models.dl.file_done": "Done",
  "models.dl.file_pending": "Pending",
  "models.dl.files": "Files",
  "models.dl.full_verify": "Full file verification",
  "models.dl.history": "Show completed downloads",
  "models.dl.history_hide": "Hide completed downloads",
  "models.dl.idle": "No downloads running",
  "models.dl.item_progress": "Item progress",
  "models.dl.label": "Downloads",
  "models.dl.last": "Last",
  "models.dl.left": "{size} remaining",
  "models.dl.list": "Download queue",
  "models.dl.log": "Installer log",
  "models.dl.log_empty": "Installer output will appear here.",
  "models.dl.log_label": "Installer output",
  "models.dl.n_active": "{n} active",
  "models.dl.n_paused": "{n} paused",
  "models.dl.n_queued": "{n} queued",
  "models.dl.none": "No downloads yet.",
  "models.dl.of": "{done} of {total}",
  "models.dl.offline_failed": "Could not enable offline mode.",
  "models.dl.offline_on": "Offline mode enabled.",
  "models.dl.overall": "Overall progress",
  "models.dl.overall_text": "{pct} overall",
  "models.dl.parallel": "Parallel downloads",
  "models.dl.parallel_failed": "Could not save the download limit.",
  "models.dl.parallel_saved": "Download limit saved.",
  "models.dl.pause_label": "Pause",
  "models.dl.paused_kept":
    "Partial files are kept. Resume continues the download.",
  "models.dl.quick_verify": "Quick verification",
  "models.dl.resume_label": "Resume",
  "models.dl.state.cancelled": "Cancelled",
  "models.dl.state.done": "Done",
  "models.dl.state.failed": "Failed",
  "models.dl.state.paused": "Paused",
  "models.dl.state.queued": "Queued",
  "models.dl.state.running": "Running",
  "models.dl.state.verifying": "Verifying",
  "models.drawer.card": "Card",
  "models.drawer.card_thing": "model card",
  "models.drawer.commit": "Commit",
  "models.drawer.commit_installed": "Commit installed",
  "models.drawer.commit_latest": "Commit latest",
  "models.drawer.compat_thing": "compatibility",
  "models.drawer.copy_id": "Copy model ID",
  "models.drawer.draft": "Draft",
  "models.drawer.facts": "Facts",
  "models.drawer.family": "Family",
  "models.drawer.files": "Files",
  "models.drawer.format": "Format",
  "models.drawer.gated": "Gated or private repository",
  "models.drawer.hf_unreachable": "Could not reach Hugging Face.",
  "models.drawer.last_used": "Last used",
  "models.drawer.legacy_line": "Legacy Splash package",
  "models.drawer.license": "License",
  "models.drawer.mlx_line": "MLX affine 4-bit · group size 64",
  "models.drawer.no_card": "No model card is available.",
  "models.drawer.tags": "Tags",
  "models.drawer.template": "Template",
  "models.drawer.template_unknown": "Available after loading the model",
  "models.drawer.title": "Model details.",
  "models.drawer.variants": "Variants",
  "models.drawer.vision": "Vision",
  "models.drawer.vision_no": "Text only",
  "models.drawer.vision_yes": "Vision available",
  "models.drawer.vision_yes_proj": "Vision · {projector}",
  "models.empty.action": "Browse supported models",
  "models.empty.body":
    "Choose a supported model to download and run on this Mac.",
  "models.empty.title": "No models installed.",
  "models.fit.fits": "Fits",
  "models.fit.tight": "Tight",
  "models.fit.tight_help":
    "Memory will be tight. Reduce context or use language-only.",
  "models.fit.wont_fit": "Won’t fit",
  "models.fit.wont_help":
    "Estimated memory exceeds this Mac’s available budget.",
  "models.format.gguf": "GGUF",
  "models.format.legacy": "Splash package",
  "models.format.mlx": "MLX 4-bit",
  "models.format.pq2": "PQ2_0",
  "models.format.unknown": "Unknown format",
  "models.manager.active": "Active",
  "models.manager.count": "{n} installed",
  "models.manager.count_loading": "Loading inventory…",
  "models.manager.downloader": "Downloader",
  "models.manager.free": "{size} free",
  "models.manager.installed": "Installed",
  "models.manager.only_active": "Only the active model is installed.",
  "models.manager.thing": "installed models",
  "models.manager.title": "Models.",
  "models.row.language_only": "Text only",
  "models.row.never_used": "Never loaded",
  "models.row.open_label": "Open",
  "models.row.pinned_title": "Pinned to this revision",
  "models.row.rev": "Revision {rev}",
  "models.row.unique": "{size} unique",
  "models.row.used": "Last used {time}",
  "models.seed.dense_gguf": "Dense model with a choice of GGUF quantizations.",
  "models.seed.dense_mlx":
    "MLX 4-bit · about 21 GB including draft and vision.",
  "models.seed.legacy": "Official Splash runtime package.",
  "models.seed.moe_gguf": "Fast MoE model with GGUF quantization options.",
  "models.seed.moe_mlx": "MLX 4-bit · about 24 GB including draft and vision.",
  "models.seed.pq2": "Prism PQ2_0 · compact dense model with vision.",
  "models.select.delete": "Delete selected",
  "models.select.delete_none": "Select models to delete",
  "models.select.row": "Row",
  "models.select.start": "Select models",
  "models.status.broken": "Broken · verify again",
  "models.status.downloading": "Downloading",
  "models.status.installed": "Installed",
  "models.status.loading": "Loading",
  "models.status.paused": "Paused",
  "models.status.pinned": "Pinned",
  "models.status.update": "Update available",
  "models.status.verifying": "Verifying",
  "models.stop.body": "Requests in flight will be interrupted.",
  "models.stop.title": "Stop the engine.",
  "models.tabs_label": "Models",
  "models.toast.already_queued": "This model is already queued.",
  "models.toast.busy":
    "The engine is serving requests. Try again when it is idle.",
  "models.toast.download_failed": "Could not download.",
  "models.toast.load_failed": "Could not load.",
  "models.toast.loading": "Loading {model}…",
  "models.toast.pause_failed": "Could not pause.",
  "models.toast.queued": "Queued {model}.",
  "models.toast.queued_size": "Queued {model} · {size}",
  "models.toast.remove_failed": "Could not remove.",
  "models.toast.resume_failed": "Could not resume.",
  "models.toast.reveal_failed": "Could not reveal.",
  "models.toast.stop_failed": "Could not stop.",
  "models.toast.stopping": "Stopping the engine…",
  "models.toast.update_failed": "Could not update.",
  "models.toast.updating": "Updating {model}…",
  "models.toast.verify_failed": "Could not verify.",
  "models.toast.verifying": "Verifying {model}…",
  "models.variant.col.bits": "Bits",
  "models.variant.col.fit": "Fit",
  "models.variant.col.size": "Size",
  "models.variant.col.status": "Status",
  "models.variant.col.tier": "Tier",
  "models.variant.col.variant": "Variant",
  "models.variant.download_label": "Download",
  "models.variant.installed": "Installed",
  "models.variant.none": "No variants are available.",
  "models.variant.projector": "Vision projector",
  "models.variant.recommended": "Recommended",
  "models.variant.unsupported": "Unsupported",
  "models.variant.unsupported_default":
    "Splash has no kernels for this tensor format.",
  "models.verify.done": "Verification completed.",
  "models.verify.failed_default":
    "The installer reported a verification error.",
  "models.verify.failed_title": "Verification failed.",
  "models.verify.failed_toast": "Could not verify the model.",
  "models.file.role.other": "Other",
  "models.file.role.draft": "Draft",
  "models.file.role.weights": "Weights",
  "models.file.role.config": "Config",
  "models.file.role.tokenizer": "Tokenizer",
  "models.file.role.mmproj": "Mmproj",
} as const;

export const t = makeT({ ...en, ...modelsStrings });
