import { en } from "./en";
import { makeT } from "./index";

export const settingsStrings = {
  "settings.page_title": "Settings",
  "settings.auto": "Auto",
  "settings.auto_for": "Auto ({value})",
  "settings.badge.next_load": "Next load",
  "settings.badge.rebind": "Reconnects the manager",
  "settings.badge.restart": "Restart",
  "settings.changed": "Changed",
  "settings.choice.model_default": "Model default",
  "settings.choice.none": "None",
  "settings.choice.not_installed": "Not installed",
  "settings.context.auto_note": "Splash chooses the largest context that fits.",
  "settings.context.footnote": "K means 1,024 tokens. Maximum: 262,144 tokens.",
  "settings.duration.toggle": "Set a request timeout",
  "settings.field.serve.max_cache_disk.label": "SSD cache limit",
  "settings.field.serve.max_context.label": "Maximum context",
  "settings.field.serve.max_memory.label": "Maximum memory",
  "settings.flags.bad_flag": "Enter a flag beginning with --.",
  "settings.flags.empty": "Enter a flag.",
  "settings.flags.value_without_flag": "A value needs a flag.",
  "settings.memory.auto_note": "Splash chooses a memory budget for this Mac.",
  "settings.memory.footnote":
    "Metal memory, including model weights and KV cache.",
  "settings.memory.ram_tick": "RAM",
  "settings.model.clear": "Clear override",
  "settings.model.inherits": "Inherits the global value",
  "settings.model.reset_to_global": "Reset to global",
  "settings.more.splash": "Splash {version}:",
  "settings.overlay.between": "{label} must be between {min} and {max}.",
  "settings.overlay.json_object": "Enter a JSON object.",
  "settings.overlay.positive": "{label} must be positive.",
  "settings.overlay.stop_empty": "Stop sequences cannot be empty.",
  "settings.overlay.stop_max": "Use at most 16 stop sequences.",
  "settings.overlay.top_k": "Top K must be -1, 0, or a positive whole number.",
  "settings.overlay.top_p": "Top P must be greater than 0 and at most 1.",
  "settings.overlay.whole_min":
    "{label} must be a whole number of at least {min}.",
  "settings.profiles.name_rule":
    "Use 1–32 lowercase letters, digits, hyphens or underscores.",
  "settings.profiles.name_taken": "This profile name is already used.",
  "settings.scope.gm_suffix": "Global or per model",
  "settings.validation.at_least": "{label} must be at least {min}.",
  "settings.validation.at_most": "{label} must be at most {max}.",
  "settings.validation.between": "{label} must be between {min} and {max}.",
  "settings.validation.host_ip": "Enter a valid IP address.",
  "settings.validation.host_name": "Enter a hostname without a scheme or path.",
  "settings.validation.number": "Enter a number.",
  "settings.validation.port": "Enter a port from 1 to 65,535.",
  "settings.validation.required": "This field is required.",
  "settings.validation.url": "Enter an HTTP or HTTPS URL.",
  "settings.value.empty_list": "None",
  "settings.value.off": "Off",
  "settings.value.on": "On",
  "settings.value.unset": "Not set",
} as const;

export const t = makeT({ ...en, ...settingsStrings });
