import { en } from "./en";
import { makeT } from "./index";

export const settingsStrings = {
  "settings.page_title": "Settings",
  "settings.auto": "Auto",
  "settings.auto_for": "Auto ({label})",
  "settings.badge.next_load": "Next load",
  "settings.badge.rebind": "Reconnects the manager",
  "settings.badge.restart": "Restart",
  "settings.changed": "Changed",
  "settings.choice.model_default": "Model default",
  "settings.choice.none": "None",
  "settings.choice.not_installed": "{model} (not installed)",
  "settings.context.auto_note": "Splash chooses the largest context that fits.",
  "settings.context.footnote": "{tokens} tokens. K means 1,024 tokens; the maximum is 262,144.",
  "settings.duration.toggle": "Set a request timeout",
  "settings.field.serve.max_cache_disk.label": "SSD cache limit",
  "settings.flags.bad_flag": "{flag} is not a flag: flags begin with --.",
  "settings.flags.empty": "Enter a flag.",
  "settings.flags.value_without_flag": "{value} needs a flag before it.",
  "settings.memory.auto_note": "Splash chooses a memory budget for this Mac.",
  "settings.memory.footnote": "{pct} of {ram}",
  "settings.memory.ram_tick": "RAM",
  "settings.model.clear": "Clear override",
  "settings.model.inherits": "Inherits the global value: {value}",
  "settings.model.reset_to_global": "Reset to global",
  "settings.more.splash": "Splash {version}:",
  "settings.overlay.between": "{label} must be between {min} and {max}.",
  "settings.overlay.json_object": "{label}: enter a JSON object.",
  "settings.overlay.positive": "{label} must be positive.",
  "settings.overlay.stop_empty": "Stop sequences cannot be empty.",
  "settings.overlay.stop_max": "Use at most 16 stop sequences.",
  "settings.overlay.top_k": "Top K must be -1, 0, or a positive whole number.",
  "settings.overlay.top_p": "{label} must be greater than 0 and at most 1.",
  "settings.overlay.whole_min":
    "{label} must be a whole number of at least {min}.",
  "settings.profiles.name_rule":
    "Use 1–32 lowercase letters, digits, hyphens or underscores.",
  "settings.profiles.name_taken": "A profile named {name} already exists.",
  "settings.scope.gm_suffix": "Global or per model",
  "settings.validation.at_least": "{label} must be at least {min}.",
  "settings.validation.at_most": "{label} must be at most {max}.",
  "settings.validation.between": "{label} must be between {min} and {max}.",
  "settings.validation.host_ip": "Enter a valid IP address.",
  "settings.validation.host_name": "Enter a hostname without a scheme or path.",
  "settings.validation.number": "Enter a number.",
  "settings.validation.port": "Enter a port from {min} to {max}.",
  "settings.validation.required": "This field is required.",
  "settings.validation.url": "Enter an HTTP or HTTPS URL.",
  "settings.value.empty_list": "None",
  "settings.value.off": "Off",
  "settings.value.on": "On",
  "settings.value.unset": "Not set",

  // page
  "settings.section.server": "Server & network",
  "settings.section.security": "Security",
  "settings.section.storage": "Models & storage",
  "settings.storage.shared_title": "Shared with your Hugging Face cache",
  "settings.storage.shared_body": "The models folder is your own Hugging Face cache at {path}. Deleting a model here can remove files you downloaded yourself with other tools.",
  "settings.section.memory": "Memory & context",
  "settings.section.cache": "Cache",
  "settings.section.performance": "Performance",
  "settings.section.requests": "Requests & limits",
  "settings.section.sampling": "Reasoning & sampling",
  "settings.section.routing": "Routing",
  "settings.section.hf": "Hugging Face",
  "settings.section.chat": "Chat & MCP",
  "settings.section.lifecycle": "Lifecycle",
  "settings.section.menubar": "Menu bar",
  "settings.section.notifications": "Notifications",
  "settings.section.data": "Data & privacy",
  "settings.section.advanced": "Advanced",
  "settings.section.about": "About",
  "settings.title": "Settings.",
  "settings.meta": "Global defaults · per-model overrides live under Models → Settings",
  "settings.meta_link": "Models",
  "settings.search": "Search settings",
  "settings.search_results.one": "{n} setting matches",
  "settings.search_results.other": "{n} settings match",
  "settings.search_none": "No setting matches {q}.",
  "settings.sections": "Settings sections",
  "settings.section_select": "Section",
  "settings.prev": "← {label}",
  "settings.next": "{label} →",
  "settings.no_fields": "Nothing to set here yet.",
  "settings.read_only": "settings.json could not be written; changes cannot be saved.",
  "settings.thing": "settings",
  "settings.thing_schema": "the settings schema",
  "settings.desc.server": "Where the API and this admin listen.",
  "settings.desc.security": "Who may call the API and open this admin.",
  "settings.security.signin_label": "Signing in",
  "settings.security.signin_body": "Sign-in is on by default. A browser signs in once with the API key and keeps a session for 12 hours; Open Admin Panel in the menu bar signs you in without typing it. The menu bar and the splash command use a token file on this Mac instead.",
  "settings.security.lan_label": "Network without TLS",
  "settings.security.lan_warn_title": "Listening on the network over plain HTTP",
  "settings.security.lan_body": "Splashboard serves plain HTTP. On a local network bind, the API key and the session cookie cross the network unencrypted, so anyone who can watch that network can read them and use them.",
  "settings.security.lan_advice": "Keep Listen on set to This Mac only. To reach Splash from other devices, put a reverse proxy with TLS (such as Caddy) in front of it on this Mac and add its host name to Allowed hosts.",
  "settings.desc.storage": "Where models and the SSD cache live.",
  "settings.desc.memory": "How much memory and context Splash may use.",
  "settings.desc.cache": "Prefix reuse in memory and on the SSD.",
  "settings.desc.performance": "Speculative decoding, batching and vision.",
  "settings.desc.requests": "Request sizes, timeouts and the queue.",
  "settings.desc.sampling": "Defaults for requests that leave a value out.",
  "settings.desc.routing": "Which model answers a request, and when models switch.",
  "settings.desc.hf": "The Hugging Face endpoint and token for downloads.",
  "settings.desc.chat": "Chat behaviour and MCP tool servers.",
  "settings.desc.lifecycle": "Start, stop, restart and idle behaviour.",
  "settings.desc.menubar": "What the menu bar icon shows.",
  "settings.desc.notifications": "Which events notify you.",
  "settings.desc.data": "What Splashboard keeps on this Mac, and clearing it.",
  "settings.desc.advanced": "Engine path, ports and other engine options.",
  "settings.desc.about": "Versions, updates and this Mac.",

  // save flow
  "settings.saved": "Settings saved.",
  "settings.saved_restarting": "Settings saved · restarting engine…",
  "settings.save_failed": "Couldn’t save settings.",
  "settings.discarded": "Changes discarded.",
  "settings.applies_on_start": "Applies when the engine starts.",
  "settings.needs_restart.one": "· {n} needs restart",
  "settings.needs_restart.other": "· {n} need restart",
  "settings.busy_title": "Restart with requests running.",
  "settings.busy_body.one": "{n} request will fail with 503. Save now and restart later instead?",
  "settings.busy_body.other": "{n} requests will fail with 503. Save now and restart later instead?",
  "settings.busy_later": "Save, restart later",
  "settings.busy_now": "Save & restart now",
  "settings.pending_restart": "Settings saved; restart the engine to apply them.",
  "settings.restart_now": "Restart now",
  "settings.rebind_title": "Moving to a new address.",
  "settings.rebind_body": "The admin will reopen at {url} in a few seconds. Bookmarks and clients must use the new address.",
  "settings.rebind_confirm": "Save & move",
  "settings.rebind_waiting": "Waiting for the manager at {url}…",
  "settings.rebind_timeout": "The manager did not answer at the new address. It may still be starting; try the link.",
  "settings.leave_title": "Discard changes.",
  "settings.leave_body.one": "{n} unsaved change will be lost.",
  "settings.leave_body.other": "{n} unsaved changes will be lost.",
  "settings.leave_keep": "Keep editing",

  // secrets
  "settings.secret.api_key": "API key",
  "settings.secret.api_key_set": "Stored in Keychain",
  "settings.secret.api_key_none": "No key.",
  "settings.secret.keychain": "Keychain ✓",
  "settings.secret.reveal": "Reveal",
  "settings.secret.hide": "Hide",
  "settings.secret.copy": "Copy",
  "settings.secret.copied": "API key copied.",
  "settings.secret.rotate": "Rotate",
  "settings.secret.generate": "Generate",
  "settings.secret.shown_once": "Shown once; copy it now.",
  "settings.secret.remask": "Hidden again in {s} s.",
  "settings.secret.rotate_title": "Rotate the API key.",
  "settings.secret.remove": "Remove",
  "settings.secret.rotate_body": "Clients using the current key stop working until they get the new one. Browsers signed in with the old key are signed out, this one included: sign in again with the new key.",
  "settings.secret.rotated": "API key rotated.",
  "settings.secret.failed": "Couldn’t change the secret.",
  "settings.secret.hf": "Hugging Face token",
  "settings.secret.hf_help": "An override stored in Keychain. Without one, downloads use your hf login token.",
  "settings.secret.hf_source.override": "Using the override",
  "settings.secret.hf_source.login": "Using hf login",
  "settings.secret.hf_source.none": "No token",
  "settings.secret.hf_enter": "Token",
  "settings.secret.hf_save": "Save override",
  "settings.secret.hf_test": "Test",
  "settings.secret.hf_ok": "Signed in as {user} ✓",
  "settings.secret.hf_bad": "The token was refused: {error}",
  "settings.secret.hf_saved": "Token saved to Keychain.",
  "settings.secret.hf_removed": "Override removed.",

  // data & privacy
  "settings.data.what": "What",
  "settings.data.size": "Size",
  "settings.data.note": "Note",
  "settings.data.actions": "Actions",
  "settings.data.clear": "Clear…",
  "settings.data.delete": "Delete…",
  "settings.data.items.one": "{n} item",
  "settings.data.items.other": "{n} items",
  "settings.data.clear_title": "Clear {what}.",
  "settings.data.clear_size": "{size} will be deleted.",
  "settings.data.clear_size_unknown": "The size is not known yet.",
  "settings.data.clear_confirm": "Clear · {size}",
  "settings.data.consequence.kv_cache": "Stops the engine first because Splash locks the cache namespace; restore points are lost.",
  "settings.data.consequence.responses": "Restarts the engine; in-process responses are lost.",
  "settings.data.consequence.default": "This cannot be undone.",
  "settings.data.cleared": "Cleared {what} · {size} freed.",
  "settings.data.failed": "Couldn’t clear {what}.",
  "settings.data.models_hint": "Opens Models with every model selected.",
  "settings.data.thing": "data sizes",
  "settings.data.footer": "No telemetry. The only network calls are to Hugging Face, GitHub releases, Homebrew and the update feed.",
  "settings.data.copy_privacy": "Copy privacy summary",
  "settings.data.privacy_summary": "Splashboard keeps everything on this Mac: models, cache, chats, usage history and logs under ~/.splash; secrets in the macOS Keychain. No telemetry. Network calls: Hugging Face (downloads), GitHub releases and Homebrew (engine updates), the app update feed.",

  // advanced
  "settings.crash.title": "Record crash traces.",
  "settings.crash.body": "Traces can contain private conversation data. Frames over 16 MiB are kept only as size and hash. Up to 4 files / 64 MiB in ~/Library/Logs/Splash/crash.",
  "settings.crash.turn_on": "Turn on",
  "settings.crash.off_title": "Keep the crash traces?",
  "settings.crash.off_body.one": "{n} trace ({size}) is still on disk.",
  "settings.crash.off_body.other": "{n} traces ({size}) are still on disk.",
  "settings.crash.off_delete.one": "Delete {n} trace · {size}",
  "settings.crash.off_delete.other": "Delete {n} traces · {size}",
  "settings.crash.keep": "Keep",
  "settings.crash.what": "crash traces",
  "settings.extra.title": "Other engine options",
  "settings.extra.count": "Splash {version} has {n} options Splashboard does not manage.",
  "settings.extra.flag": "Flag",
  "settings.extra.value": "Value",
  "settings.extra.help": "Splash --help",
  "settings.extra.remove": "Remove",
  "settings.extra.add": "Add option",
  "settings.extra.raw": "Add raw",
  "settings.extra.add_raw": "Add",
  "settings.extra.unverified": "Unverified",
  "settings.reset.title": "Reset all settings",
  "settings.reset.help": "Global and per-model settings return to their defaults.",
  "settings.reset.button": "Reset all settings",
  "settings.reset.sheet_title": "Reset all settings.",
  "settings.reset.body": "Global and per-model settings return to defaults. Storage locations, the setup state, MCP servers, models, chats, usage and secrets are kept. The engine restarts when the active model’s flags change.",
  "settings.reset.busy": "Requests are running; resetting restarts the engine and they fail with 503.",
  "settings.reset.force": "Reset & restart anyway",
  "settings.reset.result_title": "Settings reset.",
  "settings.reset.kept": "Kept as they were:",
  "settings.reset.done": "Settings reset.",
  "settings.reset.done_restart": "Settings reset · restarting engine…",
  "settings.preview": "Command preview",
  "settings.preview_help": "What the next start will run (secrets redacted).",
  "settings.preview_none": "Load a model once to preview its command.",
  "settings.preview_thing": "the command preview",
  "settings.mcp_test": "Test MCP connections",
  "settings.mcp.title": "MCP servers",
  "settings.mcp.help": "Servers whose tools Chat can call. Calls ask for confirmation unless a server is set to always allow.",
  "settings.mcp.thing": "MCP servers",
  "settings.mcp.none": "No MCP servers yet.",
  "settings.mcp.name": "Name",
  "settings.mcp.transport": "Transport",
  "settings.mcp.target": "Command or URL",
  "settings.mcp.state": "State",
  "settings.mcp.state_ok.one": "Connected · {n} tool",
  "settings.mcp.state_ok.other": "Connected · {n} tools",
  "settings.mcp.state_failed": "Failed: {error}",
  "settings.mcp.enabled": "Enabled",
  "settings.mcp.always_allow": "Always allow",
  "settings.mcp.remove": "Remove",
  "settings.mcp.remove_title": "Remove MCP server.",
  "settings.mcp.add": "Add server",
  "settings.mcp.add_title": "Add MCP server.",
  "settings.mcp.import": "Import mcp.json",
  "settings.mcp.import_title": "Import mcp.json.",
  "settings.mcp.imported.one": "Imported {n} server.",
  "settings.mcp.imported.other": "Imported {n} servers.",
  "settings.mcp.command": "Command",
  "settings.mcp.args": "Arguments (one per line)",
  "settings.mcp.env": "Environment (KEY=value per line)",
  "settings.mcp.url": "URL",
  "settings.mcp.headers": "Headers (Name: value per line)",
  "settings.mcp.name_rule": "Use 1–64 letters, digits, dots, hyphens or underscores.",
  "settings.mcp.name_taken": "A server with this name exists.",
  "settings.mcp.command_needed": "Enter the command that starts the server.",
  "settings.mcp.url_rule": "Enter an http(s) URL.",
  "settings.mcp.saved": "MCP servers saved.",
  "settings.mcp.secrets": "Secrets",
  "settings.mcp.edit": "Edit",
  "settings.mcp.edit_label": "Edit {name}",
  "settings.mcp.edit_title": "Edit MCP server.",
  "settings.mcp.save": "Save server",
  "settings.mcp.keychain_note": "Environment and header values are kept in the macOS Keychain. Saved values are shown masked and can be replaced, not read back.",
  "settings.mcp.env_saved": "Saved environment",
  "settings.mcp.env_add": "Add environment (KEY=value per line)",
  "settings.mcp.headers_saved": "Saved headers",
  "settings.mcp.headers_add": "Add headers (Name: value per line)",
  "settings.mcp.secret_replace": "Replace",
  "settings.mcp.secret_keep": "Keep saved",
  "settings.mcp.secret_undo": "Undo",
  "settings.mcp.secret_removed": "removed on save",
  "settings.mcp.secret_new": "New value for {key}",
  "settings.mcp.secret_placeholder": "New value",
  "settings.mcp.masked_echo": "That is the masked value. Paste the real value, or keep the saved one.",
  "settings.mcp.failed": "Couldn’t save the MCP servers.",
  "settings.mcp_result": "{tools} tools discovered; {errors} server errors.",
  "settings.mcp_failed": "Couldn’t discover tools.",
  "settings.json_invalid": "Enter valid JSON.",

  // notifications
  "settings.notifications.footer": "At most one notification per condition every 10 minutes. Delivered by the menu bar app, or by macOS notifications from the manager when the app is not running.",
  "settings.notifications.open": "Open macOS notification settings",

  // about
  "settings.about.app": "Splashboard",
  "settings.about.app_versions": "{gui} · manager {manager} · Python {python}",
  "settings.about.check": "Check for updates",
  "settings.about.app_check_hint": "Open the menu bar app to update.",
  "settings.about.app_checking": "Asking the menu bar app…",
  "settings.about.engine": "Splash engine",
  "settings.about.engine_line": "{version} · {source} · status schema {schema}",
  "settings.about.engine_missing": "Not installed",
  "settings.about.engine_check": "Check",
  "settings.about.up_to_date": "Up to date · checked {when}",
  "settings.about.not_checked": "Not checked yet",
  "settings.about.available": "Splash {version} available",
  "settings.about.release_notes": "Release notes",
  "settings.about.upgrade": "Upgrade Splash",
  "settings.about.upgrade_started": "Upgrading Splash…",
  "settings.about.upgrade_failed": "Couldn’t start the upgrade.",
  "settings.about.check_failed": "Couldn’t check for updates.",
  "settings.about.mac": "This Mac",
  "settings.about.mac_line": "{chip} · {cpu} CPU · {gpu} GPU · {ram} · macOS {macos}",
  "settings.about.links": "Links",
  "settings.about.gui_repo": "Repository",
  "settings.about.gui_issues": "Issues",
  "settings.about.repo": "Splash repository",
  "settings.about.issue": "Report a Splash issue",
  "settings.about.licenses": "Licenses",
  "settings.about.license_app": "Splashboard: Apache-2.0.",
  "settings.about.license_engine": "Splash and its third-party notices (llama.cpp, MIT): see THIRD_PARTY_NOTICES in the Splash repository.",
  "settings.about.license_font": "Archivo: SIL Open Font License 1.1.",
  "settings.about.license_libs": "Preact, @preact/signals, uPlot and marked: MIT. wouter-preact: Unlicense. highlight.js: BSD-3-Clause.",
  "settings.about.setup": "Setup",
  "settings.about.rerun_wizard": "Re-run welcome wizard",
  "settings.about.run_doctor": "Run doctor",
  "settings.remove.button": "Remove Splashboard data…",
  "settings.remove.title": "Remove Splashboard data",
  "settings.remove.thing": "what would be removed",
  "settings.remove.data": "Data folder {home}: settings, chats, usage history and logs ({size}).",
  "settings.remove.models": "Delete models ({size})",
  "settings.remove.cache": "Delete cache ({size})",
  "settings.remove.outside": "Kept: {path} is outside the data folder.",
  "settings.remove.type_delete": "Type DELETE to delete models or the cache",
  "settings.remove.app_connected": "The menu bar app is running. Use About → Remove Splashboard Data… in the app, which also removes its login item.",
  "settings.remove.confirm": "Remove",
  "settings.remove.failed": "Couldn’t remove Splashboard data.",
  "settings.remove.done": "Removed. {freed} freed. The manager has stopped.",
  "settings.remove.done_next": "Drag Splashboard.app to the Trash to finish.",
  "settings.about.doctor_thing": "the doctor report",
  "settings.about.diagnostics": "Logs → Diagnostics",
  "settings.about.thing_versions": "versions",
  "settings.about.thing_system": "this Mac",
  // per-model settings
  "settings.model.subtitle": "Settings for this model",
  "settings.model.back": "← Models",
  "settings.model.sections": "Model settings sections",
  "settings.model.section.overrides": "Engine overrides",
  "settings.model.section.sampling": "Sampling defaults",
  "settings.model.section.profiles": "Profiles",
  "settings.model.section.info": "Info",
  "settings.model.overrides_meta": "Effective = Splash default ← Global ← This model. Changes need a reload of this model.",
  "settings.model.save_reload": "Save & reload model",
  "settings.model.next_load": "Applies the next time this model is loaded.",
  "settings.model.thing": "model settings",
  "settings.model.sampling_meta": "Injected only when a request leaves the field out. Explicit values always win.",
  "settings.model.save_sampling": "Save defaults",
  "settings.model.sampling_saved": "Sampling defaults saved.",
  "settings.model.profiles_meta": "Overlays selected with model:profile. Explicit request fields still win.",
  "settings.model.thing_profiles": "profiles",
  "settings.model.p.profile": "Profile",
  "settings.model.p.id": "ID",
  "settings.model.p.fields": "Fields",
  "settings.model.p.actions": "Actions",
  "settings.model.p.none": "(no overlay)",
  "settings.model.p.copy_id": "Copy ID",
  "settings.model.p.edit": "Edit",
  "settings.model.p.delete": "Delete",
  "settings.model.p.reset": "Reset built-in",
  "settings.model.p.new": "New profile",
  "settings.model.p.name": "Name",
  "settings.model.p.edit_title": "Edit profile “{name}”.",
  "settings.model.p.new_title": "New profile.",
  "settings.model.p.overlay_meta": "Fields set here overlay the model’s sampling defaults when a request names {id}.",
  "settings.model.p.delete_title": "Delete profile.",
  "settings.model.p.delete_body": "{id} stops answering; requests that name it get a 404.",
  "settings.model.p.saved.one": "Profiles saved · {n} ID available.",
  "settings.model.p.saved.other": "Profiles saved · {n} IDs available.",
  "settings.model.p.failed": "Couldn’t save the profiles.",
  "settings.model.p.reserved": "default is reserved.",
  "settings.model.i.template": "Chat template",
  "settings.model.i.later": "Later system messages",
  "settings.model.i.build": "Build ID",
  "settings.model.i.layout": "Layout SHA",
  "settings.model.i.target": "Target SHA",
  "settings.model.i.kv": "KV",
  "settings.model.i.revision": "Installed revision",
  "settings.model.i.path": "Snapshot path",
  "settings.model.i.last": "Last loaded",
  "settings.model.i.context": "Context at last load",
  "settings.model.i.recorded": "Recorded",
  "settings.model.i.load_once": "— · load the model once",
  "settings.model.i.thing": "model details",
} as const;

export const t = makeT({ ...en, ...settingsStrings });
