/** Status and Usage history strings. Keys start with "status.". Common keys come from ./en. */
import { en } from './en';
import { makeT } from './index';

export const statusStrings = {
  'status.page_title': 'Status',
  'status.tabs': 'Status',
  'status.title_stopped': 'Status.',
  'status.title_model': '{name}.',
  'status.doc_title': '{chip} · {name}',
  'status.no_model': 'No model loaded.',
  'status.tokps': '{v} tok/s',

  // header meta
  'status.meta.label': 'Engine details',
  'status.meta.context': 'Context {v}',
  'status.meta.kv': 'KV {v}',
  'status.meta.vision_on': 'Vision on',
  'status.meta.vision_off': 'Vision off',
  'status.meta.draft': 'Draft {v}',
  'status.meta.draft_none': 'Draft none',
  'status.meta.uptime': 'Up {v}',
  'status.meta.version': 'Splash {v}',
  'status.meta.released': 'Weights released · reloads on next request (~1–3 s)',
  'status.meta.flushing': 'Flushing persistent cache (up to 6 s)…',

  // actions
  'status.actions.label': 'Engine actions',
  'status.actions.stop': 'Stop',
  'status.actions.restart': 'Restart',
  'status.actions.restart_engine': 'Restart engine',
  'status.actions.switch': 'Switch model',
  'status.actions.load': 'Load model',
  'status.actions.retry': 'Retry',
  'status.actions.open_downloader': 'Open Downloader',
  'status.actions.open_models': 'Open Models',
  'status.actions.open_logs': 'Open logs',
  'status.actions.no_models': 'No models installed',
  'status.actions.models_unavailable': 'The installed list is unavailable',
  'status.actions.downloading': 'Downloading {pct}',
  'status.actions.active': 'Active',
  'status.confirm.stop_title': 'Stop the engine.',
  'status.confirm.restart_title': 'Restart the engine.',
  'status.confirm.switch_title': 'Switch model.',
  'status.confirm.running.one': '{n} request is running and will fail with 503.',
  'status.confirm.running.other': '{n} requests are running and will fail with 503.',
  'status.confirm.switch_to': 'Then this model loads:',
  'status.confirm.stop': 'Stop anyway',
  'status.confirm.restart': 'Restart anyway',
  'status.confirm.switch': 'Switch anyway',
  'status.toast.stopping': 'Stopping engine…',
  'status.toast.restarting': 'Restarting engine…',
  'status.toast.loading': 'Loading {name}…',
  'status.toast.switching': 'Switching to {name}…',
  'status.toast.switch_busy': 'The engine is switching models already.',
  'status.toast.failed_stop': 'Couldn’t stop the engine.',
  'status.toast.failed_restart': 'Couldn’t restart the engine.',
  'status.toast.failed_load': 'Couldn’t load the model.',
  'status.startup_log': 'Startup log',
  'status.startup_log.template': 'Chat template · {mode}',
  'status.startup_log.command': 'Command',

  // state banners
  'status.banner.recovering': 'Engine recovering',
  'status.banner.engine_failed': 'Engine stopped',
  'status.banner.engine_failed_msg': 'Splash’s engine stopped after repeated failures.',
  'status.banner.crashed': 'Engine restarting',
  'status.banner.crashed_msg': 'Splash exited unexpectedly. Restarting in {s} s (attempt {n} of 3).',
  'status.banner.crashed_msg_now': 'Splash exited unexpectedly. Restarting (attempt {n} of 3).',
  'status.banner.ssd_title': 'SSD cache suggested',
  'status.banner.ssd_msg': 'This Mac had {avail} available at startup, which may not hold a {tokens}-token request; without the SSD cache such a request is suspended and replays its prompt.',
  'status.banner.ssd_action': 'Enable SSD cache ({size}) & restart',
  'status.banner.ssd_settings': 'Cache settings',
  'status.banner.ssd_dismiss': 'Dismiss',
  'status.banner.ssd_done': 'SSD cache set to {size} · restarting…',
  'status.banner.ssd_failed': 'Couldn’t enable the SSD cache.',
  'status.banner.hub': 'Hub notice',
  'status.banner.schema': 'Splash status schema {n} is not recognized; some panels may be empty.',

  // startup band
  'status.startup.label': 'Startup',
  'status.startup.installing': 'Preparing model…',
  'status.startup.loading': 'Loading weights…',
  'status.startup.warming': 'Warming up…',
  'status.startup.log': 'Engine output',
  'status.startup.empty': 'Waiting for the engine’s first line.',

  // failure band
  'status.failure.label': 'Startup failed',
  'status.failure.headline': 'Splash could not start this model.',
  'status.failure.raw': 'Raw output',
  'status.failure.details': 'Details',
  'status.failure.fixes': 'What to do',

  // fit sheet
  'status.fit.title': 'Model does not fit.',
  'status.fit.lead': 'Splash can hold {allowed} tokens of context for {model} on this Mac, but the setting asks for {asked}.',
  'status.fit.breakdown': 'Breakdown',
  'status.fit.and_retry': '{label} & retry',
  'status.fit.and_restart': '{label} & restart',
  'status.fit.vision_note': 'saves {bytes}; images and PDFs are rejected',
  'status.fit.applied': 'Settings updated · loading {name}…',
  'status.fit.apply_failed': 'Couldn’t update the setting.',
  'status.fit.no_budget': 'The engine printed no memory breakdown.',

  // numbers band
  'status.numbers.label': 'Numbers',
  'status.numbers.scope': 'Counter scope',
  'status.numbers.session': 'Since engine start',
  'status.numbers.all': 'All time',
  'status.numbers.clear': 'Clear GUI counters',
  'status.numbers.cleared': 'GUI counters cleared {time}',
  'status.numbers.clear_failed': 'Couldn’t clear the GUI counters.',
  'status.numbers.restarted': 'Engine restarted {time} · counters since then',
  'status.numbers.stopped': 'Engine stopped · showing — · switch to All time',
  'status.numbers.stale': 'Stale · last sample {age} ago',
  'status.numbers.usage_since': 'Recorded since {date}',
  'status.numbers.tokens': 'Tokens',
  'status.numbers.cached': 'Cached',
  'status.numbers.efficiency': 'Cache eff.',
  'status.numbers.decode': 'Decode',
  'status.numbers.prefill': 'Prefill',
  'status.numbers.draft': 'Draft acc.',
  'status.numbers.ttft': 'TTFT',
  'status.numbers.requests': 'Requests',
  'status.numbers.unit_tps': 'tok/s',
  'status.numbers.in_out': 'in {i} · out {o}',
  'status.numbers.kv_disk': 'kv {kv} · disk {disk}',
  'status.numbers.hit_rate': 'hit rate {v}',
  'status.numbers.eff_help': 'Cache efficiency is reused ÷ (reused + prefilled) tokens; the hit rate counts requests that found a cached prefix.',
  'status.numbers.cycle': 'cycle {v}',
  'status.numbers.wall': 'wall {v}',
  'status.numbers.accepted': '{a}/{d}',
  'status.numbers.p95': 'p95 {v}',
  'status.numbers.failed': '{n} failed',
  'status.numbers.cancelled': '{n} cancelled',
  'status.numbers.engine_only': 'engine only',

  // endpoints
  'status.endpoints.label': 'Endpoints',
  'status.endpoints.openai': 'OpenAI base',
  'status.endpoints.anthropic': 'Anthropic base',
  'status.endpoints.key': 'API key',
  'status.endpoints.key_off': 'Not required on this Mac',
  'status.endpoints.key_on': 'Required',
  'status.endpoints.copy_key': 'Copy key',
  'status.endpoints.key_copied': 'API key copied.',
  'status.endpoints.key_missing': 'No API key is stored.',
  'status.endpoints.key_failed': 'Couldn’t read the API key.',
  'status.endpoints.security': 'Security settings',
  'status.endpoints.lan': 'LAN',
  'status.endpoints.lan_value': 'Also on {url}',
  'status.endpoints.allowed_hosts.one': '{n} allowed host',
  'status.endpoints.allowed_hosts.other': '{n} allowed hosts',

  // live charts
  'status.charts.label': 'Live charts',
  'status.charts.window': 'Chart window',
  'status.charts.window_opt': '{n} m',
  'status.charts.pause': 'Pause',
  'status.charts.follow': 'Follow',
  'status.charts.paused': 'Paused · still collecting',
  'status.charts.no_samples': 'No samples yet',
  'status.charts.aria': '{title}, last {n} minutes, now {now}, peak {peak}',
  'status.charts.decode': 'Decode tok/s',
  'status.charts.prefill': 'Prefill tok/s',
  'status.charts.lanes': 'Lanes & queue',
  'status.charts.ttft': 'TTFT p50 / p95',
  'status.charts.memory': 'Memory',
  'status.charts.kv': 'KV pages',
  'status.charts.hit': 'Cache hit rate',
  'status.charts.disk': 'Disk cache I/O',
  'status.charts.s.decode': 'decode',
  'status.charts.s.prefill': 'prefill',
  'status.charts.s.decoding': 'decoding',
  'status.charts.s.prefilling': 'prefilling',
  'status.charts.s.queued': 'queued',
  'status.charts.s.waiting': 'waiting for resources',
  'status.charts.s.p50': 'p50',
  'status.charts.s.p95': 'p95',
  'status.charts.s.charged': 'charged',
  'status.charts.s.current': 'current',
  'status.charts.s.peak': 'peak',
  'status.charts.s.limit': 'limit',
  'status.charts.s.active': 'active',
  'status.charts.s.cache': 'cache',
  'status.charts.s.free': 'free',
  'status.charts.s.hit': 'hit rate',
  'status.charts.s.eff': 'cache efficiency',
  'status.charts.s.read': 'read',
  'status.charts.s.written': 'written',
  'status.charts.lanes_missing': 'Lanes are not reported by this Splash version.',
  'status.charts.ssd_off': 'SSD cache off',
  'status.charts.values': 'Values',
  'status.charts.values_caption': 'Last 10 samples',
  'status.charts.time': 'Time',
  'status.charts.empty_none': 'Nothing to serve yet.',
  'status.charts.empty_none_body': 'Download a model to start.',
  'status.charts.empty_stopped': 'No model loaded.',
  'status.charts.empty_stopped_body': 'Load one to start serving on port {port}.',
  'status.charts.backfill_failed': 'chart history',

  // memory band

  // cache band
  'status.cache.settings': 'Cache settings',

  // scheduler band

  // latency band

  'status.band.stopped': 'Engine stopped.',
  'status.band.missing': 'Not reported by this Splash version.',

  // Claude Code band

} as const;

export const t = makeT({ ...en, ...statusStrings });
