/** Status and Usage history strings (docs/ui/02). Keys start with "status.". Common keys come from ./en. */
import { en } from './en';
import { makeT } from './index';

export const statusStrings = {
  'status.page_title': 'Status',
  'status.tabs': 'Status',
  'status.title_stopped': 'Status.',
  'status.title_model': '{name}.',
  'status.doc_title': '{chip} · {name}',
  'status.no_model': 'No model loaded.',
  'status.tokps': '{v} tok/s',

  // header meta (docs/ui/02 §4)
  'status.meta.label': 'Engine details',
  'status.meta.context': 'Context {v}',
  'status.meta.kv': 'KV {v}',
  'status.meta.vision_on': 'Vision on',
  'status.meta.vision_off': 'Vision off',
  'status.meta.draft': 'Draft {v}',
  'status.meta.draft_none': 'Draft none',
  'status.meta.uptime': 'Up {v}',
  'status.meta.version': 'Splash {v}',
  'status.meta.released': 'Weights released · reloads on next request (~1–3 s)',
  'status.meta.flushing': 'Flushing persistent cache (up to 6 s)…',

  // actions
  'status.actions.label': 'Engine actions',
  'status.actions.stop': 'Stop',
  'status.actions.restart': 'Restart',
  'status.actions.restart_engine': 'Restart engine',
  'status.actions.switch': 'Switch model',
  'status.actions.load': 'Load model',
  'status.actions.retry': 'Retry',
  'status.actions.open_downloader': 'Open Downloader',
  'status.actions.open_models': 'Open Models',
  'status.actions.open_logs': 'Open logs',
  'status.actions.no_models': 'No models installed',
  'status.actions.models_unavailable': 'The installed list is unavailable',
  'status.actions.downloading': 'Downloading {pct}',
  'status.actions.active': 'Active',
  'status.confirm.stop_title': 'Stop the engine.',
  'status.confirm.restart_title': 'Restart the engine.',
  'status.confirm.switch_title': 'Switch model.',
  'status.confirm.running.one': '{n} request is running and will fail with 503.',
  'status.confirm.running.other': '{n} requests are running and will fail with 503.',
  'status.confirm.switch_to': 'Then this model loads:',
  'status.confirm.stop': 'Stop anyway',
  'status.confirm.restart': 'Restart anyway',
  'status.confirm.switch': 'Switch anyway',
  'status.toast.stopping': 'Stopping engine…',
  'status.toast.restarting': 'Restarting engine…',
  'status.toast.loading': 'Loading {name}…',
  'status.toast.switching': 'Switching to {name}…',
  'status.toast.switch_busy': 'The engine is switching models already.',
  'status.toast.failed_stop': 'Couldn’t stop the engine.',
  'status.toast.failed_restart': 'Couldn’t restart the engine.',
  'status.toast.failed_load': 'Couldn’t load the model.',
  'status.startup_log': 'Startup log',
  'status.startup_log.template': 'Chat template · {mode}',
  'status.startup_log.command': 'Command',

  // state banners (docs/ui/02 §10)
  'status.banner.recovering': 'Engine recovering',
  'status.banner.engine_failed': 'Engine stopped',
  'status.banner.engine_failed_msg': 'Splash’s engine stopped after repeated failures.',
  'status.banner.crashed': 'Engine restarting',
  'status.banner.crashed_msg': 'Splash exited unexpectedly. Restarting in {s} s (attempt {n} of 3).',
  'status.banner.crashed_msg_now': 'Splash exited unexpectedly. Restarting (attempt {n} of 3).',
  'status.banner.ssd_title': 'SSD cache suggested',
  'status.banner.ssd_msg': 'This Mac had {avail} available at startup, which may not hold a {tokens}-token request; without the SSD cache such a request is suspended and replays its prompt.',
  'status.banner.ssd_action': 'Enable SSD cache ({size}) & restart',
  'status.banner.ssd_settings': 'Cache settings',
  'status.banner.ssd_dismiss': 'Dismiss',
  'status.banner.ssd_done': 'SSD cache set to {size} · restarting…',
  'status.banner.ssd_failed': 'Couldn’t enable the SSD cache.',
  'status.banner.hub': 'Hub notice',
  'status.banner.schema': 'Splash status schema {n} is not recognized; some panels may be empty.',

  // startup band
  'status.startup.label': 'Startup',
  'status.startup.installing': 'Preparing model…',
  'status.startup.loading': 'Loading weights…',
  'status.startup.warming': 'Warming up…',
  'status.startup.log': 'Engine output',
  'status.startup.empty': 'Waiting for the engine’s first line.',

  // failure band
  'status.failure.label': 'Startup failed',
  'status.failure.headline': 'Splash could not start this model.',
  'status.failure.raw': 'Raw output',
  'status.failure.details': 'Details',
  'status.failure.fixes': 'What to do',

  // fit sheet (docs/ui/02 §11.1)
  'status.fit.title': 'Model does not fit.',
  'status.fit.lead': 'Splash can hold {allowed} tokens of context for {model} on this Mac, but the setting asks for {asked}.',
  'status.fit.breakdown': 'Breakdown',
  'status.fit.and_retry': '{label} & retry',
  'status.fit.and_restart': '{label} & restart',
  'status.fit.vision_note': 'saves {bytes}; images and PDFs are rejected',
  'status.fit.applied': 'Settings updated · loading {name}…',
  'status.fit.apply_failed': 'Couldn’t update the setting.',
  'status.fit.no_budget': 'The engine printed no memory breakdown.',

  // numbers band (docs/ui/02 §5)
  'status.numbers.label': 'Numbers',
  'status.numbers.scope': 'Counter scope',
  'status.numbers.session': 'Since engine start',
  'status.numbers.all': 'All time',
  'status.numbers.clear': 'Clear GUI counters',
  'status.numbers.cleared': 'GUI counters cleared {time}',
  'status.numbers.clear_failed': 'Couldn’t clear the GUI counters.',
  'status.numbers.restarted': 'Engine restarted {time} · counters since then',
  'status.numbers.stopped': 'Engine stopped · showing — · switch to All time',
  'status.numbers.stale': 'Stale · last sample {age} ago',
  'status.numbers.usage_since': 'Recorded since {date}',
  'status.numbers.tokens': 'Tokens',
  'status.numbers.cached': 'Cached',
  'status.numbers.efficiency': 'Cache eff.',
  'status.numbers.decode': 'Decode',
  'status.numbers.prefill': 'Prefill',
  'status.numbers.draft': 'Draft acc.',
  'status.numbers.ttft': 'TTFT',
  'status.numbers.requests': 'Requests',
  'status.numbers.unit_tps': 'tok/s',
  'status.numbers.in_out': 'in {i} · out {o}',
  'status.numbers.kv_disk': 'kv {kv} · disk {disk}',
  'status.numbers.hit_rate': 'hit rate {v}',
  'status.numbers.eff_help': 'Cache efficiency is reused ÷ (reused + prefilled) tokens; the hit rate counts requests that found a cached prefix.',
  'status.numbers.cycle': 'cycle {v}',
  'status.numbers.wall': 'wall {v}',
  'status.numbers.accepted': '{a}/{d}',
  'status.numbers.p95': 'p95 {v}',
  'status.numbers.failed': '{n} failed',
  'status.numbers.cancelled': '{n} cancelled',
  'status.numbers.engine_only': 'engine only',

  // endpoints (docs/ui/02 §6)
  'status.endpoints.label': 'Endpoints',
  'status.endpoints.openai': 'OpenAI base',
  'status.endpoints.anthropic': 'Anthropic base',
  'status.endpoints.key': 'API key',
  'status.endpoints.key_off': 'Not required on this Mac',
  'status.endpoints.key_on': 'Required',
  'status.endpoints.copy_key': 'Copy key',
  'status.endpoints.key_copied': 'API key copied.',
  'status.endpoints.key_missing': 'No API key is stored.',
  'status.endpoints.key_failed': 'Couldn’t read the API key.',
  'status.endpoints.security': 'Security settings',
  'status.endpoints.lan': 'LAN',
  'status.endpoints.lan_value': 'Also on {url}',
  'status.endpoints.allowed_hosts.one': '{n} allowed host',
  'status.endpoints.allowed_hosts.other': '{n} allowed hosts',

  // live charts (docs/ui/02 §7)
  'status.charts.label': 'Live charts',
  'status.charts.window': 'Chart window',
  'status.charts.window_opt': '{n} m',
  'status.charts.pause': 'Pause',
  'status.charts.follow': 'Follow',
  'status.charts.paused': 'Paused · still collecting',
  'status.charts.no_samples': 'No samples yet',
  'status.charts.aria': '{title}, last {n} minutes, now {now}, peak {peak}',
  'status.charts.decode': 'Decode tok/s',
  'status.charts.prefill': 'Prefill tok/s',
  'status.charts.lanes': 'Lanes & queue',
  'status.charts.ttft': 'TTFT p50 / p95',
  'status.charts.memory': 'Memory',
  'status.charts.kv': 'KV pages',
  'status.charts.hit': 'Cache hit rate',
  'status.charts.disk': 'Disk cache I/O',
  'status.charts.s.decode': 'decode',
  'status.charts.s.prefill': 'prefill',
  'status.charts.s.decoding': 'decoding',
  'status.charts.s.prefilling': 'prefilling',
  'status.charts.s.queued': 'queued',
  'status.charts.s.waiting': 'waiting for resources',
  'status.charts.s.p50': 'p50',
  'status.charts.s.p95': 'p95',
  'status.charts.s.charged': 'charged',
  'status.charts.s.current': 'current',
  'status.charts.s.peak': 'peak',
  'status.charts.s.limit': 'limit',
  'status.charts.s.active': 'active',
  'status.charts.s.cache': 'cache',
  'status.charts.s.free': 'free',
  'status.charts.s.hit': 'hit rate',
  'status.charts.s.eff': 'cache efficiency',
  'status.charts.s.read': 'read',
  'status.charts.s.written': 'written',
  'status.charts.lanes_missing': 'Lanes are not reported by this Splash version.',
  'status.charts.ssd_off': 'SSD cache off',
  'status.charts.values': 'Values',
  'status.charts.values_caption': 'Last 10 samples',
  'status.charts.time': 'Time',
  'status.charts.empty_none': 'Nothing to serve yet.',
  'status.charts.empty_none_body': 'Download a model to start.',
  'status.charts.empty_stopped': 'No model loaded.',
  'status.charts.empty_stopped_body': 'Load one to start serving on port {port}.',
  'status.charts.backfill_failed': 'chart history',

  // memory band (docs/ui/02 §8.1)
  'status.memory.label': 'Memory',
  'status.memory.meter': 'Memory charged of limit',
  'status.memory.charged': 'Charged of limit',
  'status.memory.charged_v': '{c} of {l}',
  'status.memory.current': 'Current · peak',
  'status.memory.allocated': 'allocated {v}',
  'status.memory.headroom': 'Headroom',
  'status.memory.host': 'Host available · reserve',
  'status.memory.host_of': 'of {ram} RAM · host headroom {v}',
  'status.memory.pressure': 'Pressure',
  'status.memory.pressure.normal': 'Normal',
  'status.memory.pressure.warning': 'Warning',
  'status.memory.pressure.critical': 'Critical',
  'status.memory.top_pressure': 'engine memory_pressure: {v}',
  'status.memory.growth': 'Growth',
  'status.memory.growth.allowed': 'allowed',
  'status.memory.growth.denied': 'denied',
  'status.memory.denied': '{n} denied reservations',
  'status.memory.metal': 'Metal',
  'status.memory.metal_ok': 'healthy',
  'status.memory.metal_failed': 'failed: {reason}',
  'status.memory.explainer': 'Metal allocations, not process RSS.',

  // cache band (docs/ui/02 §8.2)
  'status.cache.label': 'Cache',
  'status.cache.ram': 'RAM',
  'status.cache.pages': 'KV pages {a} active · {c} cached · {f} free of {t}',
  'status.cache.kv_bytes': 'KV bytes {b} ({r} reclaimable)',
  'status.cache.states': 'states {n} ({u} in use, {b})',
  'status.cache.checkpoints': 'checkpoints {list}',
  'status.cache.evictions': 'evictions {n}',
  'status.cache.ssd': 'SSD tier',
  'status.cache.ssd_meter': 'SSD cache used of capacity',
  'status.cache.ssd_used': '{u} of {c}',
  'status.cache.on_disk': 'on disk {v}',
  'status.cache.kv_blocks': 'KV blocks {n} ({b})',
  'status.cache.demotions': 'demotions {n} · refused {r} · pending pages {p}',
  'status.cache.restores': 'restores {n}',
  'status.cache.disk_hits': 'disk hits {h} · promotions {p} · offloads {o}',
  'status.cache.wear': 'read {r} · written {w} this session',
  'status.cache.off': 'Off',
  'status.cache.settings': 'Cache settings',
  'status.cache.persistent': 'Persistent',
  'status.cache.persistent_on': 'On · {dir}',
  'status.cache.persistent_off': 'Off · keeps the SSD cache across restarts',
  'status.cache.taken_back': 'Restored at start: {s} states, {k} blocks, {b}, {l} left behind',
  'status.cache.write_behind': 'write-behind waiting {w} · durable {d} · unneeded {u} · refused {r}',
  'status.cache.failures': 'Failures',
  'status.cache.f.copies': 'copies',
  'status.cache.f.restores': 'restores',
  'status.cache.f.offloads': 'offloads',
  'status.cache.f.demotions': 'demotions',
  'status.cache.f.replay': 'replay publications',
  'status.cache.raw_failed': 'raw engine status',

  // scheduler band (docs/ui/02 §8.3)
  'status.sched.label': 'Scheduler & admission',
  'status.sched.waiting': 'Waiting',
  'status.sched.waiting_v': '{t} total · {m} memory · {c} concurrency · {p} shared prefix · {g} grammar mask',
  'status.sched.held': 'Held · restoring · suspended · draining',
  'status.sched.held_v': '{h} held · {r} restoring · {s} suspended · draining {d}',
  'status.sched.oldest': 'Oldest wait',
  'status.sched.suspensions': 'Suspensions',
  'status.sched.suspensions_v': '{r} resource · {p} priority · {m} resumed',
  'status.sched.lanes': 'Lanes now',
  'status.sched.lanes_v': '{p} prefilling · {d} decoding · {q} queued · {w} waiting for resources',
  'status.sched.batches': 'Decode batches',
  'status.sched.batches_aria': 'Decode batches by width: {list}',
  'status.sched.loop': 'Loop',
  'status.sched.loop_v': 'max tick {v}',

  // latency band (docs/ui/02 §8.4)
  'status.latency.label': 'Latency',
  'status.latency.caption': 'Latency per request stage',
  'status.latency.stage': 'Stage',
  'status.latency.p50': 'p50',
  'status.latency.p95': 'p95',
  'status.latency.mean': 'Mean',
  'status.latency.count': 'Count',
  'status.latency.approx': '≈ {v}',
  'status.latency.note': 'p50 and p95 are estimated from Splash’s cumulative histogram buckets.',
  'status.latency.missing': 'Not reported by this Splash version.',
  'status.latency.raw': 'Raw buckets',
  'status.latency.raw_stage': 'Stage',
  'status.latency.bound': 'At most (s)',
  'status.latency.cumulative': 'Cumulative count',
  'status.latency.s.http_request': 'HTTP request',
  'status.latency.s.upload': 'Upload',
  'status.latency.s.preparation_queue': 'Preparation queue',
  'status.latency.s.preparation': 'Preparation',
  'status.latency.s.template': 'Template',
  'status.latency.s.tokenization': 'Tokenization',
  'status.latency.s.grammar': 'Grammar',
  'status.latency.s.images': 'Images',
  'status.latency.s.native_queue': 'Native queue',
  'status.latency.s.http_ttft': 'Time to first token',
  'status.latency.s.output_interval': 'Output interval',

  'status.band.stopped': 'Engine stopped.',
  'status.band.missing': 'Not reported by this Splash version.',

  // Claude Code band (docs/ui/02 §9)
  'status.claude.label': 'Claude Code',
  'status.claude.model': 'Model',
  'status.claude.command': 'Command',
  'status.claude.env': 'Environment variables',
  'status.claude.reveal': 'Reveal key',
  'status.claude.hide': 'Hide key',
  'status.claude.copy_env': 'Copy',
  'status.claude.copied': 'Copied',
  'status.claude.alias': '{id} (alias)',
  'status.claude.profile': '{id}',
  'status.claude.stopped': 'The command starts the engine if needed.',
  'status.claude.footer': 'Session-only: plain claude keeps its own account.',
  'status.claude.integrations': 'Integrations',
  'status.claude.integrations_more': 'for Codex, OpenCode, Hermes and Pi.',
  'status.claude.no_model': 'No model to pick yet.',

  // Usage history (docs/ui/02 §12)
  'status.history.page_title': 'Usage history',
  'status.history.title': 'Usage history.',
  'status.history.filters': 'Filters',
  'status.history.from': 'From',
  'status.history.to': 'To',
  'status.history.model': 'Model',
  'status.history.endpoint': 'Endpoint',
  'status.history.status': 'Status',
  'status.history.client': 'Client',
  'status.history.all': 'All',
  'status.history.reset': 'Reset',
  'status.history.export': 'Export CSV',
  'status.history.totals': 'Totals',
  'status.history.t.requests': 'Requests',
  'status.history.t.in': 'Tokens in',
  'status.history.t.out': 'Out',
  'status.history.t.cached': 'Cached',
  'status.history.t.failed': 'Failed',
  'status.history.t.ttft': 'p50 TTFT',
  'status.history.tokens_day': 'Tokens per day',
  'status.history.tokens_day_aria': 'Tokens per day per model',
  'status.history.other': 'other',
  'status.history.day': 'Day',
  'status.history.heatmap': 'Hourly heatmap',
  'status.history.heatmap_aria': 'Requests by weekday and hour',
  'status.history.heatmap_cell.one': '{day} {hour}:00 · {n} request',
  'status.history.heatmap_cell.other': '{day} {hour}:00 · {n} requests',
  'status.history.heatmap_hint': 'Use the arrow keys to read each hour.',
  'status.history.heatmap_none': 'No requests in this range.',
  'status.history.hour': 'Hour',
  'status.history.requests_time': 'Requests over time',
  'status.history.s.requests': 'requests',
  'status.history.s.errors': 'failed',
  'status.history.top_clients': 'Top clients',
  'status.history.c.client': 'Client',
  'status.history.c.requests': 'Requests',
  'status.history.c.tokens': 'Tokens',
  'status.history.c.last': 'Last seen',
  'status.history.c.unknown': 'unknown',
  'status.history.log': 'Request log',
  'status.history.l.time': 'Time',
  'status.history.l.model': 'Model:profile',
  'status.history.l.endpoint': 'Endpoint',
  'status.history.l.client': 'Client',
  'status.history.l.status': 'Status',
  'status.history.l.in': 'In',
  'status.history.l.cached': 'Cached',
  'status.history.l.out': 'Out',
  'status.history.l.ttft': 'TTFT',
  'status.history.l.dur': 'Dur',
  'status.history.l.injected': 'Injected',
  'status.history.injected.one': '{n} field',
  'status.history.injected.other': '{n} fields',
  'status.history.injected_show': 'Show the fields injected into request {id}',
  'status.history.page_range': 'Rows {a}–{b}',
  'status.history.prev': 'Newer',
  'status.history.next': 'Older',
  'status.history.empty': 'No requests recorded.',
  'status.history.empty_body': 'Usage appears after the first request through the proxy.',
  'status.history.open_chat': 'Open Chat',
  'status.history.loading': 'Loading usage',
  'status.history.thing.summary': 'usage totals',
  'status.history.thing.timeseries': 'usage over time',
  'status.history.thing.heatmap': 'the hourly heatmap',
  'status.history.thing.clients': 'top clients',
  'status.history.thing.requests': 'the request log',
  'status.history.st.2xx': '2xx',
  'status.history.st.4xx': '4xx',
  'status.history.st.5xx': '5xx',
  'status.history.wd.0': 'Mon',
  'status.history.wd.1': 'Tue',
  'status.history.wd.2': 'Wed',
  'status.history.wd.3': 'Thu',
  'status.history.wd.4': 'Fri',
  'status.history.wd.5': 'Sat',
  'status.history.wd.6': 'Sun',
} as const;

export const t = makeT({ ...en, ...statusStrings });
