/** Tools strings (docs/ui/08). Keys start with "tools.". Common keys come from ./en. */
import { en } from './en';
import { makeT } from './index';

export const toolsStrings = {
  'tools.page_title': 'Tools',
  'tools.tabs': 'Tools',
  'tools.title.playground': 'Playground.',
  'tools.title.tokenizer': 'Tokenizer.',
  'tools.title.judgments': 'Judgments.',
  'tools.title.benchmark': 'Benchmark.',
  'tools.not_loaded': 'No model is loaded.',
  'tools.not_loaded_auto': 'Requests will start {model} through auto-load, which adds a few seconds.',
  'tools.not_loaded_manual': 'Load one from Models first.',
  'tools.load_now': 'Load now',
  'tools.open_models': 'Open models',
  'tools.load_failed': 'Couldn’t load the model.',
  'tools.needs_ready': 'Needs a loaded model.',
  'tools.model': 'Model',

  // JSON editor
  'tools.json.format': 'Format',
  'tools.json.valid': 'Valid ✓',
  'tools.json.invalid': 'Invalid ✗',
  'tools.json.error': 'Line {line}, column {col}: {msg}',

  // playground (08 §1)
  'tools.pg.request': 'Request',
  'tools.pg.response': 'Response',
  'tools.pg.endpoint': 'Endpoint',
  'tools.pg.group.openai': 'OpenAI',
  'tools.pg.group.anthropic': 'Anthropic',
  'tools.pg.group.tokenizer': 'Tokenizer',
  'tools.pg.group.scoring': 'Scoring',
  'tools.pg.group.health': 'Health',
  'tools.pg.param.response_id': 'Response id',
  'tools.pg.param.model_id': 'Model id',
  'tools.pg.param_missing': 'Enter the {name}.',
  'tools.pg.param_response': 'A response id looks like resp_….',
  'tools.pg.mode': 'Mode',
  'tools.pg.mode.profiles': 'Through profiles',
  'tools.pg.mode.raw': 'Raw to engine',
  'tools.pg.mode_help.profiles': 'Same path as your apps. Defaults and profiles are injected; the request is logged in usage history.',
  'tools.pg.mode_help.raw': 'Straight to Splash on its internal port. Nothing is injected, the model must be the loaded one, and the request is not counted in usage.',
  'tools.pg.raw_tag': 'Raw',
  'tools.pg.raw_needs_engine': 'Raw mode needs a running engine',
  'tools.pg.template': 'Template',
  'tools.pg.body': 'Body',
  'tools.pg.headers': 'Headers',
  'tools.pg.headers_auth': 'Authorization: Bearer •••• is added for you while you are signed in.',
  'tools.pg.headers_none': 'Content-Type: application/json is fixed; no other headers are needed.',
  'tools.pg.send': 'Send',
  'tools.pg.stop': 'Stop',
  'tools.pg.copy_as': 'Copy as',
  'tools.pg.copy.curl': 'curl',
  'tools.pg.copy.python_openai': 'Python (openai)',
  'tools.pg.copy.python_anthropic': 'Python (anthropic)',
  'tools.pg.copy.js_fetch': 'JavaScript (fetch)',
  'tools.pg.copy_disabled': 'Only /v1/messages routes',
  'tools.pg.copied': 'Copied {what}.',
  'tools.pg.view.raw': 'Raw',
  'tools.pg.view.parsed': 'Parsed',
  'tools.pg.view.headers': 'Headers',
  'tools.pg.views': 'Response view',
  'tools.pg.col.n': '#',
  'tools.pg.col.t': 'T+ms',
  'tools.pg.col.event': 'Event',
  'tools.pg.col.data': 'Data',
  'tools.pg.footer': '{n} events · first data {fd} · first token {ft} · done {done}',
  'tools.pg.status': '{status} · {secs} s',
  'tools.pg.raw_header': 'Raw · engine',
  'tools.pg.idle': 'Send a request to see the response.',
  'tools.pg.parsed.text': 'Text',
  'tools.pg.parsed.reasoning': 'Reasoning',
  'tools.pg.parsed.tools': 'Tool calls',
  'tools.pg.parsed.usage': 'Usage',
  'tools.pg.parsed.timings': 'Timings',
  'tools.pg.parsed.progress': 'Progress',
  'tools.pg.parsed.error': 'Error',
  'tools.pg.header': 'Header',
  'tools.pg.value': 'Value',
  'tools.pg.request_failed': 'The request failed.',
  'tools.pg.history': 'History',
  'tools.pg.history_meta': 'Last 50, this browser',
  'tools.pg.history_clear': 'Clear',
  'tools.pg.history_clear_q': 'Clear the history?',
  'tools.pg.history_empty': 'No requests yet.',
  'tools.pg.history_delete': 'Delete',
  'tools.pg.history_truncated': 'Attachment data was not kept in history.',
  'tools.pg.history_load': 'Load {method} {path} into the editor',

  'tools.template.chat': 'Chat',
  'tools.template.chat_tools': 'Chat + tools',
  'tools.template.chat_image': 'Chat + image',
  'tools.template.chat_pdf': 'Chat + PDF',
  'tools.template.json_schema': 'JSON schema',
  'tools.template.progress': 'Streaming with progress',
  'tools.template.string_prompt': 'String prompt',
  'tools.template.token_ids': 'Token IDs',
  'tools.template.responses_basic': 'Basic (store)',
  'tools.template.responses_continue': 'Continue with previous_response_id',
  'tools.template.responses_reasoning': 'Reasoning effort',
  'tools.template.messages_basic': 'Basic',
  'tools.template.messages_thinking': 'Thinking enabled',
  'tools.template.messages_document': 'Document (PDF)',
  'tools.template.messages_tools': 'Tools',
  'tools.template.count_text': 'Text',
  'tools.template.count_image': 'With image',
  'tools.template.tokenize': 'Tokenize',
  'tools.template.apply_template': 'Apply template',
  'tools.template.semif': 'SemIf example',
  'tools.template.systemone': 'System One example',

  // tokenizer (08 §2)
  'tools.tok.tabs': 'Tokenizer views',
  'tools.tok.tab.tokenize': 'Tokenize',
  'tools.tok.tab.template': 'Template',
  'tools.tok.tab.count': 'Count (Anthropic)',
  'tools.tok.text': 'Text',
  'tools.tok.add_special': 'Add special tokens',
  'tools.tok.add_special_help': 'Adds the tokenizer’s own BOS/EOS as a raw prompt would.',
  'tools.tok.run': 'Tokenize',
  'tools.tok.tokens.one': '{n} token',
  'tools.tok.tokens.other': '{n} tokens',
  'tools.tok.view': 'View',
  'tools.tok.view.pieces': 'Pieces',
  'tools.tok.view.ids': 'IDs only',
  'tools.tok.copy_ids': 'Copy IDs',
  'tools.tok.chip_tip': 'id {id} · {bytes} bytes',
  'tools.tok.copied_id': 'Copied id {id}.',
  'tools.tok.pieces_note': 'IDs come from /tokenize; pieces from the model’s own tokenizer files, decoded one ID at a time.',
  'tools.tok.ids_only': 'Pieces are unavailable for this model; showing IDs only.',
  'tools.tok.messages': 'Messages (Chat shape)',
  'tools.tok.tools': 'Tools (optional)',
  'tools.tok.options': 'Options',
  'tools.tok.effort': 'Reasoning effort',
  'tools.tok.effort_default': 'Model default',
  'tools.tok.kwargs': 'Template kwargs',
  'tools.tok.gen_prompt': 'Add generation prompt',
  'tools.tok.render': 'Render',
  'tools.tok.rendered': 'Rendered prompt',
  'tools.tok.rendered_meta': '{tokens} tokens · {special} special',
  'tools.tok.whitespace': 'Show whitespace',
  'tools.tok.mode': 'Template mode',
  'tools.tok.mode_value': 'later system: {v}',
  'tools.tok.template_help': 'Image parts keep textual placeholders; use Count (Anthropic) for image-aware counts.',
  'tools.tok.system': 'System',
  'tools.tok.add_image': '+ Add image',
  'tools.tok.count': 'Count',
  'tools.tok.input_tokens': 'Input tokens',
  'tools.tok.count_help': 'Counts images the way the model sees them, unlike raw tokenization.',
  'tools.tok.failed': 'Splash refused the request.',

  // judgments (08 §3)
  'tools.jd.tabs': 'Judgment kinds',
  'tools.jd.tab.systemone': 'System One',
  'tools.jd.tab.semif': 'SemIf',
  'tools.jd.caveat': 'Local model scores, not calibrated confidence. Calibrate on held-out data before using thresholds.',
  'tools.jd.clef_title': 'This is a Clef backbone, but not Clef.',
  'tools.jd.clef_body': 'Splash scores with the model’s output layer at single-token answer slots; Cloudflare’s Clef uses its joint schema head over all options. Answers and confidence will differ from Clef’s.',
  'tools.jd.clef_link': 'Learn more',
  'tools.jd.state': 'State',
  'tools.jd.state_kind': 'State format',
  'tools.jd.state.text': 'Text',
  'tools.jd.state.json': 'JSON',
  'tools.jd.state_invalid': 'The state is not valid JSON.',
  'tools.jd.questions': 'Questions',
  'tools.jd.count': '{n} / 64',
  'tools.jd.add.noul': '+ Noul',
  'tools.jd.add.choice': '+ Choice',
  'tools.jd.add.score': '+ Score',
  'tools.jd.max_questions': 'Splash accepts at most 64 questions per request',
  'tools.jd.remove': 'Remove',
  'tools.jd.key': 'Key',
  'tools.jd.instructions': 'Instructions',
  'tools.jd.criteria': 'Criteria',
  'tools.jd.criteria_noul': 'Criteria (optional: true / false descriptions)',
  'tools.jd.true': 'true',
  'tools.jd.false': 'false',
  'tools.jd.label': 'Label',
  'tools.jd.description': 'Description (optional)',
  'tools.jd.add_label': '+ Add label',
  'tools.jd.levels': 'Levels (ordered, low → high)',
  'tools.jd.add_level': '+ Add level',
  'tools.jd.key_empty': 'Enter a key.',
  'tools.jd.key_dup': 'Keys must be unique.',
  'tools.jd.domain': 'Use 1–255 entries.',
  'tools.jd.label_empty': 'Labels cannot be empty.',
  'tools.jd.label_dup': 'Labels must be unique.',
  'tools.jd.edit_json': 'Edit as JSON',
  'tools.jd.json_unrepresentable': 'This JSON can’t be shown in the builder; edit it here.',
  'tools.jd.run': 'Run',
  'tools.jd.copy_typesafe': 'Copy as typesafe-sdk Python',
  'tools.jd.copy_curl': 'Copy as curl',
  'tools.jd.results': 'Results',
  'tools.jd.results_meta': '{tokens} prompt tokens · {secs} s',
  'tools.jd.answer': 'Answer',
  'tools.jd.answer_v': 'Answer {v}',
  'tools.jd.confidence': 'Confidence {v}',
  'tools.jd.confidence_tip': '1 − H(p) / log K — entropy concentration over the K options, not calibrated accuracy.',
  'tools.jd.score_v': 'Score {v} / {k}',
  'tools.jd.no_inference': 'No inference',
  'tools.jd.error_details': 'Error details',
  'tools.jd.id': 'ID',
  'tools.jd.question': 'Question',
  'tools.jd.options': 'Options',
  'tools.jd.options_count': '{n} / 16',
  'tools.jd.add_option': '+ Add option',
  'tools.jd.min_options': 'Add at least two options.',
  'tools.jd.max_options': 'SemIf rows take at most 16 options',
  'tools.jd.option_id': 'id',
  'tools.jd.option_dup': 'Option ids must be unique.',
  'tools.jd.result': 'Result',
  'tools.jd.logit': 'logit {v}',
  'tools.jd.p': 'p {v}',
  'tools.jd.sha': 'prompt_sha256 {v}',
  'tools.jd.answer_tokens': 'answer tokens {v}',
  'tools.jd.usage': '{n} prompt tokens · 0 completion tokens (scoring generates nothing)',
  'tools.jd.failed': 'Splash refused the request.',

  // benchmark (08 §4)
  'tools.bm.lead': 'Measures this Mac with the loaded model. Runs at foreground priority; other requests will wait.',
  'tools.bm.scenarios': 'Scenarios',
  'tools.bm.samples': 'Samples per scenario',
  'tools.bm.samples_help': '1–10, one warmup first.',
  'tools.bm.s.decode_short': 'Decode, short prompt',
  'tools.bm.s.cold_prefill': 'Cold prefill',
  'tools.bm.s.cached_ttft': 'Cached TTFT',
  'tools.bm.s.concurrency': 'Concurrency',
  'tools.bm.d.decode_short': '128-token prompt · max_tokens 512 · ignore_eos · effort none · temp 0',
  'tools.bm.d.cold_prefill': '2K / 8K / 32K salted code-like prompts · max_tokens 1',
  'tools.bm.d.cached_ttft': 'The 32K prompt replayed · reports TTFT and cache_n',
  'tools.bm.d.concurrency': '1 · 2 · 3 · 4 parallel short-prompt streams · aggregate tok/s',
  'tools.bm.needs_ctx': 'Needs ≥ {need} context (loaded model: {have})',
  'tools.bm.before': 'Before you run',
  'tools.bm.native_note': 'Splash’s own native benchmarks (make test-performance-real) need a source checkout and are not used here.',
  'tools.bm.run': 'Run benchmark',
  'tools.bm.estimate': 'Estimated {min}–{max} min',
  'tools.bm.running': 'Running',
  'tools.bm.cancel': 'Cancel',
  'tools.bm.cancelled': 'Benchmark cancelled; the completed scenarios were saved.',
  'tools.bm.start_failed': 'Couldn’t start the benchmark.',
  'tools.bm.progress': 'Benchmark progress',
  'tools.bm.progress_line': '{scenario} · {pct} · {elapsed} elapsed',
  'tools.bm.saved': 'Saved runs',
  'tools.bm.none': 'No benchmark runs yet.',
  'tools.bm.compare': 'Compare ({n} selected)',
  'tools.bm.open': 'Open',
  'tools.bm.delete': 'Delete',
  'tools.bm.delete_title': 'Delete benchmark run.',
  'tools.bm.delete_body': 'The run from {when} with {model} is removed from usage.db.',
  'tools.bm.select': 'Select run {when} for comparison',
  'tools.bm.state.running': 'Running',
  'tools.bm.state.done': 'Done',
  'tools.bm.state.cancelled': 'Cancelled',
  'tools.bm.state.failed': 'Failed',
  'tools.bm.run_title': 'Run {when}',
  'tools.bm.close': 'Back to runs',
  'tools.bm.export': 'Export JSON',
  'tools.bm.copy_summary': 'Copy summary',
  'tools.bm.h.decode': 'Decode tok/s',
  'tools.bm.h.prefill': 'Prefill tok/s',
  'tools.bm.h.cold_ttft': 'Cold TTFT',
  'tools.bm.h.cached_ttft': 'Cached TTFT',
  'tools.bm.h.aggregate': 'Aggregate tok/s',
  'tools.bm.sample': 'Sample',
  'tools.bm.median': 'Median',
  'tools.bm.compare_title': 'Compare',
  'tools.bm.col.select': 'Select',
  'tools.bm.col.when': 'When',
  'tools.bm.col.engine': 'Engine',
  'tools.bm.col.state': 'State',
  'tools.pg.col.actions': 'Actions',
  'tools.bm.compare_differs': 'Runs differ in model/engine; compare with care.',
  'tools.bm.thing_runs': 'benchmark runs',
  'tools.bm.thing_run': 'this run',
  'tools.bm.thing_preflight': 'the pre-run checks',
} as const;

export const t = makeT({ ...en, ...toolsStrings });
