/** Usage history strings. Keys start with "usage.". Kept apart from ./status so the
 * Status route's initial bundle does not carry them. Common keys come from ./en. */
import { en } from './en';
import { makeT } from './index';

export const usageStrings = {
  // Usage history
  'usage.history.page_title': 'Usage history',
  'usage.history.title': 'Usage history.',
  'usage.history.filters': 'Filters',
  'usage.history.from': 'From',
  'usage.history.to': 'To',
  'usage.history.model': 'Model',
  'usage.history.endpoint': 'Endpoint',
  'usage.history.status': 'Status',
  'usage.history.client': 'Client',
  'usage.history.all': 'All',
  'usage.history.reset': 'Reset',
  'usage.history.export': 'Export CSV',
  'usage.history.totals': 'Totals',
  'usage.history.t.requests': 'Requests',
  'usage.history.t.in': 'Tokens in',
  'usage.history.t.out': 'Out',
  'usage.history.t.cached': 'Cached',
  'usage.history.t.failed': 'Failed',
  'usage.history.t.ttft': 'p50 TTFT',
  'usage.history.tokens_day': 'Tokens per day',
  'usage.history.tokens_day_aria': 'Tokens per day per model',
  'usage.history.other': 'other',
  'usage.history.day': 'Day',
  'usage.history.heatmap': 'Hourly heatmap',
  'usage.history.heatmap_aria': 'Requests by weekday and hour',
  'usage.history.heatmap_cell.one': '{day} {hour}:00 · {n} request',
  'usage.history.heatmap_cell.other': '{day} {hour}:00 · {n} requests',
  'usage.history.heatmap_hint': 'Use the arrow keys to read each hour.',
  'usage.history.heatmap_none': 'No requests in this range.',
  'usage.history.hour': 'Hour',
  'usage.history.requests_time': 'Requests over time',
  'usage.history.s.requests': 'requests',
  'usage.history.s.errors': 'failed',
  'usage.history.top_clients': 'Top clients',
  'usage.history.c.client': 'Client',
  'usage.history.c.requests': 'Requests',
  'usage.history.c.tokens': 'Tokens',
  'usage.history.c.last': 'Last seen',
  'usage.history.c.unknown': 'unknown',
  'usage.history.log': 'Request log',
  'usage.history.l.time': 'Time',
  'usage.history.l.model': 'Model:profile',
  'usage.history.l.endpoint': 'Endpoint',
  'usage.history.l.client': 'Client',
  'usage.history.l.status': 'Status',
  'usage.history.l.in': 'In',
  'usage.history.l.cached': 'Cached',
  'usage.history.l.out': 'Out',
  'usage.history.l.ttft': 'TTFT',
  'usage.history.l.dur': 'Dur',
  'usage.history.l.injected': 'Injected',
  'usage.history.injected.one': '{n} field',
  'usage.history.injected.other': '{n} fields',
  'usage.history.injected_show': 'Show the fields injected into request {id}',
  'usage.history.page_range': 'Rows {a}–{b}',
  'usage.history.page_range_total': 'Rows {a}–{b} of {total}',
  'usage.history.heatmap_tokens.one': '{day} {hour}:00 · {n} request · {tokens} tokens',
  'usage.history.heatmap_tokens.other': '{day} {hour}:00 · {n} requests · {tokens} tokens',
  'usage.history.st.cancelled': 'cancelled',
  'usage.history.thing.facets': 'the filter options',
  'usage.history.prev': 'Newer',
  'usage.history.next': 'Older',
  'usage.history.empty': 'No requests recorded.',
  'usage.history.empty_body': 'Usage appears after the first request through the proxy.',
  'usage.history.open_chat': 'Open Chat',
  'usage.history.loading': 'Loading usage',
  'usage.history.thing.summary': 'usage totals',
  'usage.history.thing.timeseries': 'usage over time',
  'usage.history.thing.heatmap': 'the hourly heatmap',
  'usage.history.thing.clients': 'top clients',
  'usage.history.thing.requests': 'the request log',
  'usage.history.st.2xx': '2xx',
  'usage.history.st.4xx': '4xx',
  'usage.history.st.5xx': '5xx',
  'usage.history.wd.0': 'Mon',
  'usage.history.wd.1': 'Tue',
  'usage.history.wd.2': 'Wed',
  'usage.history.wd.3': 'Thu',
  'usage.history.wd.4': 'Fri',
  'usage.history.wd.5': 'Sat',
  'usage.history.wd.6': 'Sun',
} as const;

export const t = makeT({ ...en, ...usageStrings });
