import { en } from "./en";
import { makeT } from "./index";

export const welcomeStrings = {
  "welcome.page_title": "Welcome",
  "welcome.title": "Welcome.",
  "welcome.thing_setup": "setup",
  "welcome.finish_failed": "Couldn’t finish setup.",
  // step 3 (docs/ui/04 §4)
  "welcome.usecase.lead": "What will you use this for? This sets sensible defaults; every one can be changed later.",
  "welcome.usecase.label": "Use case",
  "welcome.usecase.applies": "What this applies",
  "welcome.usecase.col.setting": "Setting",
  "welcome.usecase.col.flag": "Flag",
  "welcome.usecase.col.now": "Now",
  "welcome.usecase.col.next": "This preset",
  "welcome.usecase.unchanged": "(unchanged)",
  "welcome.usecase.default": "(default)",
  "welcome.usecase.ram_tip": "Splash’s startup check decides; the GUI retries with the largest size that fits.",
  "welcome.usecase.thing": "the presets",
  "welcome.usecase.apply_failed": "Couldn’t apply the preset.",
  // step 4 (docs/ui/04 §5)
  "welcome.model.lead": "Choose your first model.",
  "welcome.model.reason": "For {preset} on a {ram} Mac we recommend:",
  "welcome.model.recommended": "Recommended",
  "welcome.model.alternatives": "Alternatives",
  "welcome.model.language_only": "Language-only",
  "welcome.model.installed": "Installed",
  "welcome.model.use": "Use this model",
  "welcome.model.selected": "Selected",
  "welcome.model.download": "Download",
  "welcome.model.download_size": "Download · {size}",
  "welcome.model.wont_fit": "Needs ≈ {size}",
  "welcome.model.browse": "Browse all",
  "welcome.model.continue_note": "You can continue while it downloads.",
  "welcome.model.thing": "the recommendation",
  "welcome.model.queued": "Queued {model}.",
  "welcome.model.download_failed": "Couldn’t start the download.",
  // step 5 (docs/ui/04 §6)
  "welcome.start.lead": "Start the server.",
  "welcome.start.ready_title": "Ready.",
  "welcome.start.download": "Download",
  "welcome.start.load": "Load model & start server",
  "welcome.start.load_help": "Starts Splash with your settings. The first load takes a few seconds.",
  "welcome.start.waiting_download": "Waiting for the download to finish.",
  "welcome.start.phase.installing": "Preparing",
  "welcome.start.phase.loading": "Loading weights",
  "welcome.start.phase.warming": "Warming up",
  "welcome.start.phase.ready": "Ready",
  "welcome.start.log": "Engine log",
  "welcome.start.failed": "Splash could not start this model.",
  "welcome.start.retry": "Retry",
  "welcome.start.choose_other": "Choose another model",
  "welcome.start.no_model": "No model yet.",
  "welcome.start.no_model_body": "Download one to start serving; the server runs without a model until then.",
  "welcome.start.back_model": "Back to First model",
  "welcome.start.finish_anyway": "Finish anyway",
  "welcome.start.endpoints": "Endpoints",
  "welcome.start.openai": "OpenAI base",
  "welcome.start.anthropic": "Anthropic base",
  "welcome.start.key": "API key",
  "welcome.start.key_off": "Not required on this Mac",
  "welcome.start.key_on": "Required · copy it from Settings → Security",
  "welcome.start.try": "Try it",
  "welcome.start.next": "Next",
  "welcome.start.open_chat": "Open Chat",
  "welcome.start.agents": "Connect coding agents",
  "welcome.start.open_status": "Open Status",
  "welcome.start.path": "The splash command is at ~/.splash/bin/splash. Add it to PATH?",
  "welcome.start.path_help": "Adds one line to ~/.zprofile and ~/.bash_profile inside a marked block.",
  "welcome.start.path_add": "Add to PATH",
  "welcome.start.path_done": "Added. Open a new terminal to use splash.",
  "welcome.start.path_failed": "Couldn’t update PATH.",
  "welcome.start.path_on": "splash is on PATH.",
  "welcome.start.close_hint": "You can close this window.",
  "welcome.start.load_failed": "Couldn’t load the model.",
  "welcome.start.moving": "Moving to {url}…",
  "welcome.engine.brew_command": "Homebrew install command",
  "welcome.engine.brew_found": "Homebrew found.",
  "welcome.engine.brew_install": "Install Homebrew",
  "welcome.engine.brew_missing": "Homebrew is not installed.",
  "welcome.engine.brew_not_needed": "Splash is already installed.",
  "welcome.engine.brew_open_again": "Open Terminal again",
  "welcome.engine.brew_still_waiting":
    "Finish the installation in Terminal, then check again.",
  "welcome.engine.brew_unknown": "Homebrew has not been checked.",
  "welcome.engine.brew_waiting": "Waiting for Homebrew installation…",
  "welcome.engine.brew_web_hint":
    "Open Terminal and run the official Homebrew installer.",
  "welcome.engine.brew_yourself": "Install Homebrew in Terminal",
  "welcome.engine.brew_yourself_body":
    "Homebrew may ask for your Mac password. Return here when it finishes.",
  "welcome.engine.check_again": "Check again",
  "welcome.engine.checking": "Checking this Mac…",
  "welcome.engine.checks_label": "System checks",
  "welcome.engine.copy_log": "Copy installation log",
  "welcome.engine.doctor": "Run diagnostics",
  "welcome.engine.install_unavailable":
    "Install Splash in Terminal to continue.",
  "welcome.engine.installed": "Splash is installed.",
  "welcome.engine.lead": "Check this Mac and install the Splash engine.",
  "welcome.engine.log_waiting": "Waiting for installer output…",
  "welcome.engine.mac_value": "{chip} · macOS {version}",
  "welcome.engine.needs_brew": "Install Homebrew first.",
  "welcome.engine.open_terminal_cmd": "Open in Terminal",
  "welcome.engine.perms_ok": "Private data directory",
  "welcome.engine.retry": "Retry installation",
  "welcome.engine.row.brew": "Homebrew",
  "welcome.engine.row.mac": "Mac and macOS",
  "welcome.engine.row.permissions": "Data permissions",
  "welcome.engine.row.shell": "Shell command",
  "welcome.engine.row.splash": "Splash",
  "welcome.engine.shell_error": "Could not check shell configuration.",
  "welcome.engine.shell_fix":
    "Remove the splash function or alias from your shell configuration.",
  "welcome.engine.shell_ok": "No conflicting splash command found.",
  "welcome.engine.shell_unknown": "Shell configuration has not been checked.",
  "welcome.engine.shell_what":
    "A shell function or alias can hide the Splash GUI command.",
  "welcome.engine.splash_command": "Splash install command",
  "welcome.engine.splash_failed": "Splash installation failed.",
  "welcome.engine.splash_install": "Install Splash",
  "welcome.engine.splash_installing": "Installing Splash…",
  "welcome.engine.splash_log": "Installation output",
  "welcome.engine.splash_missing": "Splash is not installed.",
  "welcome.engine.terminal_failed": "Could not open Terminal.",
  "welcome.engine.too_old": "Update Splash to version 1.2.0 or newer.",
  "welcome.engine.untested":
    "This Splash version has not been tested with this GUI.",
  "welcome.engine.upgrade": "Upgrade Splash",
  "welcome.foot.label": "Wizard navigation",
  "welcome.glyph.fail": "Failed",
  "welcome.glyph.ok": "Ready",
  "welcome.glyph.pending": "Checking",
  "welcome.glyph.skip": "Skipped",
  "welcome.glyph.warn": "Warning",
  "welcome.import.done": "Import completed.",
  "welcome.import.draft": "Shared draft",
  "welcome.import.failed": "Import failed.",
  "welcome.import.found": "Found {n} repositories in the default cache.",
  "welcome.import.label": "Import existing downloads",
  "welcome.import.move": "Move selected repositories",
  "welcome.import.move_help":
    "Existing downloads move into the Splash models directory.",
  "welcome.import.moving": "Moving files…",
  "welcome.import.thing": "cached models",
  "welcome.import.unavailable":
    "Could not inspect the default Hugging Face cache.",
  "welcome.key.serve_max_context": "Maximum context",
  "welcome.mac_meta": "{chip} · {memory}",
  "welcome.nav.back": "Back",
  "welcome.nav.continue": "Continue",
  "welcome.nav.skip": "Skip setup",
  "welcome.rail.done": "Completed",
  "welcome.rail.label": "Setup steps",
  "welcome.save_failed": "Could not save setup progress.",
  "welcome.skip.toast": "Setup skipped. You can run it again from Settings.",
  "welcome.step.engine": "Engine",
  "welcome.step.model": "First model",
  "welcome.step.start": "Start",
  "welcome.step.storage": "Storage and server",
  "welcome.step.usecase": "Use case",
  "welcome.step_meta": "Step {n} of 5 · {name}",
  "welcome.storage.change": "Change…",
  "welcome.storage.change_cache": "Change cache directory",
  "welcome.storage.change_models": "Change models directory",
  "welcome.storage.contains": "Contains {size}",
  "welcome.storage.default_cache": "Default: ~/.splash/cache",
  "welcome.storage.default_models": "Default: ~/.splash/models",
  "welcome.storage.free": "{size} free",
  "welcome.storage.key_clients":
    "Clients must include this key when authentication is enabled.",
  "welcome.storage.key_failed": "Could not generate an API key.",
  "welcome.storage.key_making": "Generating key…",
  "welcome.storage.key_off": "No API key required on this Mac",
  "welcome.storage.key_once": "Copy this key for your clients.",
  "welcome.storage.key_regenerate": "Generate a new key",
  "welcome.storage.key_set": "API key is set",
  "welcome.storage.key_stored": "Stored in the macOS Keychain.",
  "welcome.storage.lead": "Choose storage locations and how clients connect.",
  "welcome.storage.login_help":
    "Start the menu bar app and manager when you log in.",
  "welcome.storage.path_invalid": "Choose an absolute directory path.",
  "welcome.storage.pick_failed": "Could not select that directory.",
  "welcome.storage.port_applies": "The new port applies at the end of setup.",
  "welcome.storage.port_checking": "Checking port…",
  "welcome.storage.port_current": "Current manager port",
  "welcome.storage.port_free": "Port is available.",
  "welcome.storage.port_in_use": "This port is already in use.",
  "welcome.storage.port_legacy":
    "Port 9999 is used by the previous Splash shell setup.",
  "welcome.storage.port_range": "Choose a port from 1 to 65,535.",
  "welcome.storage.row.cache": "Cache directory",
  "welcome.storage.row.key": "API key",
  "welcome.storage.row.login": "Launch at login",
  "welcome.storage.row.models": "Models directory",
  "welcome.storage.row.port": "Server port",
  "welcome.storage.same_volume": "Models and cache share this volume.",
  "welcome.storage.settings": "Storage settings",
  "welcome.storage.sheet.cache": "Cache directory.",
  "welcome.storage.sheet.default": "Use default",
  "welcome.storage.sheet.help":
    "Choose an empty directory. Existing data can be moved from Storage settings.",
  "welcome.storage.sheet.models": "Models directory.",
  "welcome.storage.sheet.path": "Directory path",
  "welcome.storage.sheet.use": "Use this directory",
  "welcome.unknown_chip": "Apple silicon",
  "welcome.value.disk_off": "SSD cache off",
  "welcome.value.model_default": "Model default",
  "welcome.value.off": "Off",
  "welcome.value.on": "On",
} as const;

export const t = makeT({ ...en, ...welcomeStrings });
